### ISSUE TITLE
Investigate adding missing typings warning 

### ISSUE THREAD

**Issue by wmonk** [wmonk/create-react-app-typescript#10]
As per #8 there can be some confusion for TS beginners around missing module errors that are actually to do with missing typings. `react-scripts` has done a great job with making more subtle errors more digestible and obvious. So my thinking is an addition of a nicer message about installing @types/ or adding a type patch for it, with a link how to do it.

**Comment by majodev** [comment]
Might be no longer needed since TypeScript 2.1: [Allow untyped imports](https://github.com/Microsoft/TypeScript/pull/11889).

**Comment by noelmace** [comment]
Nope, this issue is still their with TS 2.2. I tried to add this to init, but it doesn't seems to work, and I can't figure out why : 

```javascript
if (useYarn) {
    command = 'yarnpkg';
    args = ['add'];
    devArgs = ['add', '--dev'];
  } else {
    command = 'npm';
    args = [
      'install',
      '--save',
      verbose && '--verbose'
    ].filter(function(e) { return e; });
    devArgs = [
      'install',
      '--save-dev',
      verbose && '--verbose'
    ].filter(function(e) { return e; });
  }
  args.push('react', 'react-dom');
  devArgs.push('@types/node', '@types/react', '@types/react-dom', '@types/jest');

  // Install devDependencies (typings, etc ...)
  console.log('Installing devDependencies using ' + command + '...');
  console.log();
  var devProc = spawn.sync(command, devArgs, {stdio: 'inherit'});
  if (devProc.status !== 0) {
    console.error('`' + command + ' ' + args.join(' ') + '` failed');
    return;
  }
```

**Comment by CraigglesO** [comment]
OOPS, posted on the wrong issue.


I am using Yarn:

I had an error that said
`cannot find name ' require'`

But it still ran great (to be clear, this error ran inside atom with the atom-typescript plugin)


But this fixed it (tsconfig.json):
```
  "compilerOptions": {
      ...
      "types": [
        "node"
      ],
      "typeRoots": [
        "node_modules/@types"
      ]
  }
```

I am also having an issue with `cannot find name "it"`, (app.test.tsx) But I am sure I will find eventually and get back with you.
