### ISSUE TITLE
Allow loading of TypeScript files from node_modules directory

### ISSUE THREAD

**Issue by harrygr** [wmonk/create-react-app-typescript#105]
My project has some dependencies that are written in TypeScript that I `yarn link` to the project's node_modules directory in development. Currently I can only use these dependencies if I first compile them to JS. It would be nice just to be able to import the typescript directly, however the compiler gives me the following error:

```
Module parse failed: <path-to-dep>.tsx Unexpected token (7:7)
You may need an appropriate loader to handle this file type.
<file contents...>
```

This is clearly down to the [webpack config](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/config/webpack.config.dev.js#L186-L188) only including files in the app path for `ts-loader`. 

Would there be a problem with adding module_modules to this, or otherwise allowing a way to include other paths that contain typescript without having to eject?

**Comment by wmonk** [comment]
Hi @harrygr, yes this would be an issue. Generally speaking you shouldn't be compiling your dependencies, they should be distributed in plain js. You can eject and update the webpack config yourself if you'd like this behaviour.

This is probably less problematic than running babel across all node_modules. But beware it will likely slow down your builds.

**Comment by harrygr** [comment]
Fair enough. The dependencies in question are my own and are developed alongside the app itself. E.g. a component library external to my project.
As mentioned it's `yarn link`ed to my project which effectively symlinks the dependency into node_modules.
Currently I have to rebuild a dependency every time I make a change (and probably first removing the output directory of the dep which requires my project's dev server to be restarted). 
I can set up a file watcher for the changes, but it make the dev flow a bit more cumbersome. Are there any approaches to improve this flow?
