### ISSUE TITLE
Make a new release with TS 2.4

### ISSUE THREAD

**Issue by gyzerok** [wmonk/create-react-app-typescript#106]
Hi @wmonk!

Can you, please, make a new release since https://github.com/wmonk/create-react-app-typescript/pull/94 got merged?

**Comment by wmonk** [comment]
Done and released in 2.4.0!

**Comment by gyzerok** [comment]
Hm, for some reason after updating I get `Module build failed: Error: Cannot find module 'typescript'`. Any ideas what it might mean?

**Comment by wmonk** [comment]
Not sure im afraid, CI seems to be running fine in a fresh environment so it might be something locally.

**Comment by wmonk** [comment]
I've just tried creating a new project and it's working fine. Could you `rm -rf` your node modules and try installing again.

**Comment by gyzerok** [comment]
Seems to work now. Not sure however if that is reinstallation of `node_modules` which solved the issue. Anyway thank you for help!
