### ISSUE TITLE
Value is missing in types declaration in version 2.4.0 

### ISSUE THREAD

**Issue by KatSick** [wmonk/create-react-app-typescript#107]
Looks like react typing are incompatible with TS 2.4.1

try to create `<select value=""/>`

Than error:

`(33,11): error TS2339: Property 'value' does not exist on type 'DetailedHTMLProps<SelectHTMLAttributes<HTMLSelectElement>, HTMLSelectElement>'.`

**Comment by jaredpalmer** [comment]
Yeah DefintelyTyped push a mistake where they forgot to add `<select value="">` and various other errors to 15.0.37. Really annoying.

**Comment by KatSick** [comment]
Thanks. 15.0.30 fixed the issue
