### ISSUE TITLE
Consider moving ts-lint rules into their own package

### ISSUE THREAD

**Issue by timjacobi** [wmonk/create-react-app-typescript#109]
Momentarily the `tslint.json` that is created is fairly huge and adding own rules is a bit of a pain so it would be nice if these rules could be moved into their own package from which the `tslint.json` could be extended. Happy to provide a PR.

**Comment by wmonk** [comment]
Yes agree with this. I originally just used my own rules, not thinking this package would take off! I will happily accept a PR for this. 👍

**Comment by timjacobi** [comment]
Sound. I'll get the ball rolling.

**Comment by wmonk** [comment]
Closing to follow the open PR
