### ISSUE TITLE
how to get rid of /static

### ISSUE THREAD

**Issue by xblox** [wmonk/create-react-app-typescript#111]
Hi,
I am a little confused to see in build/index.html the absolute prefix /static. Is there a way to get rid of it, same for the included hash ? 

Problem is that the app has to be served as sub-dir somewhere and so it won't work.

I also had a look at the 'ejected' version, but can't find the location to change such thing.
g

**Comment by xblox** [comment]
found it, you have to define homepage in package.json; please have some updated readme.md

**Comment by wmonk** [comment]
Glad you found it. I will happily accept a PR to update the readme with a link to the original create react app for first look issues.
