### ISSUE TITLE
Best way for typescript version lowering? 

### ISSUE THREAD

**Issue by NZainchkovskiy** [wmonk/create-react-app-typescript#114]
I trying to use this project with Office Fabric UI components (for SharePoint development). These components have an issues with typescript versions above 2.2.2. So I want to lower typescript version but still use this project. What's the best way to do it? Just edit package.json? I'm noticed that typescript is dependency of main package. So I need to lower whole package version? If so, how can I install certain version from the beginning? 
Thank you!

**Comment by ianschmitz** [comment]
For reference: #85

**Comment by wmonk** [comment]
Tracking in #85
