### ISSUE TITLE
Enabling webpack hot module reloading?

### ISSUE THREAD

**Issue by stevenmusumeche** [wmonk/create-react-app-typescript#118]
I looked through previous issues and could not find an answer to this.  I had hot module reloading working previous with the JS version of create-react-app.  After converting it to typescript, everything works well except for hot module reloading.  The reloading actually does happen, but any typescript React components are not updating unless I do a full page refresh.  

Has anyone got this working with typescript?

**Comment by wmonk** [comment]
As this issue hasn't been updated for a while, I am going to close it. If there are any updates feel free to re-open and comment. 👍

**Comment by stevenmusumeche** [comment]
I understand.  It's not resolved (HMR doesn't work), but there has been no comment or activity.

**Comment by alexwebbb** [comment]
howdy

As of [Typescript 2.0](https://tinyurl.com/j8xro5g) (https://tinyurl.com/j8xro5g)

Hot module namespace errors are easily resolved by running

yarn add @types/webpack
yarn add @types/webpack-env

or the equivalent 

npm install @types/webpack --save
npm install @types/webpack-env --save

Perhaps this will resolve your issue? I was able to get it working with [this style](https://tinyurl.com/y7gzcqqm) (https://tinyurl.com/y7gzcqqm) of hot module reloading.

**Comment by jcrben** [comment]
upstream work seems to be at https://github.com/facebookincubator/create-react-app/pull/2304
