### ISSUE TITLE
NODE_PATH set in .env doesn't work

### ISSUE THREAD

**Issue by pacemkr** [wmonk/create-react-app-typescript#119]
Fresh app. Then:

```
echo NODE_PATH=src > .env
```

And change `src/index.tsx`
```
import App from './App';
```
to
```
import App from 'App';
```

Results in:
```
./src/index.tsx
(3,17): error TS2307: Cannot find module 'App'.
```

This is one way to get absolute imports with plain `create-react-app`, I tested the same process with that and it builds fine.

The `.env` file itself is definitely loaded, since I can set `PORT`, for example.

Related:
#98
https://github.com/facebookincubator/create-react-app/issues/741
https://github.com/facebookincubator/create-react-app/pull/1712
(possibly) https://github.com/facebookincubator/create-react-app/issues/2230

**Comment by pacemkr** [comment]
It seems typescript doesn't support the NODE_PATH env variable: https://github.com/Microsoft/TypeScript/issues/8760

Putting my local modules under `src/node_modules` worked for me with no other changes.

**Comment by zhenwenc** [comment]
The most easy way to solve this issue is by forking this repository, and update the webpack config yourself. Just add `paths.appSrc` to the `resolve.modules` config (in both prod and dev) would work:
```
    modules: ['node_modules', paths.appNodeModules, paths.appSrc].concat(
      // It is guaranteed to exist because we tweak it in `env.js`
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
    ),
```
So that you don't need to eject, just keep your fork in sync time to time. Hope that helps :-)

**Comment by constfun** [comment]
@zhenwenc So far as I can tell that achieves the same result as setting NODE_PATH=src in the .env file. `process.env.NODE_PATH.split(path.delimiter).filter(Boolean)`

I still don't have a solution, btw... putting code in `src/node_modules` is asking for trouble, so I didn't do this in the end.
