### ISSUE TITLE
How to use Create-React-App + TypeScript + Ant-Design without Eject

### ISSUE THREAD

**Issue by comerc** [wmonk/create-react-app-typescript#124]
[react-app-rewired](https://github.com/timarney/react-app-rewired) + [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader) = [babel-plugin-import](https://github.com/ant-design/babel-plugin-import)

[boilerplate project](https://github.com/comerc/cra-ts-antd)

happy coding!

**Comment by wmonk** [comment]
Do you have an issue, or are you asking a question? Please update the description to make this clear.
