### ISSUE TITLE
Project not specified to tslint

### ISSUE THREAD

**Issue by pelotom** [wmonk/create-react-app-typescript#126]
When you first start a freshly-scaffolded app, the following warning flashes:

```sh
Warning: The 'no-use-before-declare' rule requires type infomation.
```

This is because `--project` is not being specified to `tslint`. It has the implication that any rules that require type information are disabled. In the ejected app's webpack config, adding

```js
options: {
  typeCheck: true,
  tsConfigFile: paths.appTsConfig,
}
```

to the `ts-loader` config fixes it.

**Comment by wmonk** [comment]
I will accept a PR for this.

**Comment by lilred** [comment]
I would be interested in implementing this PR, but I don't know where the added options go. (I imagine in `packages/react-scripts/config/webpack.config.*.js`?)

If @pelotom could elaborate I will definitely open a PR.

**Comment by pelotom** [comment]
I've since discovered that `tslint-loader` [has serious performance problems when in type checking mode](https://github.com/wbuchwalter/tslint-loader/issues/76). Because of this I've stopped using `tslint-loader` and opted instead for [`tslint-webpack-plugin`](https://www.npmjs.com/package/tslint-webpack-plugin).

**Comment by DorianGrey** [comment]
Should no longer be a problem due to the inclusion of `fork-ts-checker-webpack-plugin`, which provides the  required `ts.Program` instance `tslint`'s type-checking.
Note that this is currently only on master, not released.
