### ISSUE TITLE
Add Sass support

### ISSUE THREAD

**Issue by TheGrimSilence** [wmonk/create-react-app-typescript#128]
When choosing Typescript over Javascript it is often to utilize better features. In the same case, many developers such as myself would like to utilize SCSS over the standard CSS to utilize its features. It'd be as simple as adding sass-loader, css-loader, and style-loader all together inside of the webpack configuration files to work with the server and build scripts.

**Comment by wmonk** [comment]
We are following the create-react-app project so will implement it if they do.
