### ISSUE TITLE
Merge react-scripts with upstream

### ISSUE THREAD

**Issue by Oceanswave** [wmonk/create-react-app-typescript#129]
A few desirable changes have recently landed in upstream react-scripts -- Most notably the usage of webpack 3.x which brings some nice build speed improvements.

It would be great if these could land in create-react-app-typescript

**Comment by wmonk** [comment]
Yup there is an open PR for this at the moment. I am on holiday currently so won't be able to work on it until next week at the earliest.

**Comment by ianschmitz** [comment]
I believe webpack 3 still hasn't landed in an official release of react-scripts just yet. Looks to be slated for their 1.0.11 release.

https://github.com/facebookincubator/create-react-app/pull/2574
