### ISSUE TITLE
Import untranspiled files from module

### ISSUE THREAD

**Issue by vincaslt** [wmonk/create-react-app-typescript#131]
Is there a way to import untranspiled files from node_modules? I see this line under webpack config: "Make sure your source files are compiled, as they will not be processed in any way.", but if I eject, is there a way to make it transpile the imported files along with the project? Basically I want to have commonly shared files package, which I use accross other typescript applications, but linked via package.json. Basically what happens now, is webpack tries to import the files form node modules as javascript files, and breaks on typescript syntax.

**Comment by wmonk** [comment]
No this is not possible unless you eject. I would not recommend this approach either. I would recommend distributing packages as javascript. You can supplement with typings to take advantage of TS.
