### ISSUE TITLE
Suggestion: Support for webpack `alias` (for use in `tsconfig`).

### ISSUE THREAD

**Issue by nottoseethesun** [wmonk/create-react-app-typescript#132]
Support for customizing [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) in `webpack.config.js` would reduce pain when moving modules around in a project, per the post, [how-to-avoid-relative-path-hell-javascript-typescript-projects](https://goenning.net/2017/07/21/how-to-avoid-relative-path-hell-javascript-typescript-projects/) .

A change to `tsconfig.json` is needed, but that is already under control of users of `create-react-app-typescript`.

**Comment by wmonk** [comment]
I would consider a pull request for this. I don't generally want to deviate from the `create-react-app` project, and this sounds like it'd be an issue.

**Comment by sergeyzwezdin** [comment]
It's related to #138 I've created. If you're able to add `.env` support for this it would be helpful.

**Comment by wmonk** [comment]
Think we're tracking this in #122. Please re-open if this isn't the same issue.
