### ISSUE TITLE
Version 2.6.0 not on npm

### ISSUE THREAD

**Issue by corydeppen** [wmonk/create-react-app-typescript#137]
Is there something preventing 2.6.0 from being published to npm? The changelog for this repo shows 2.6.0 as the latest, so I was expecting to see it on npm.

I'm also not sure of the effort required, but I'm looking forward to react-scripts 1.0.11 being merged, which upgrades Webpack to v3.

**Comment by wmonk** [comment]
Completely accidental! Published now 🎉
