### ISSUE TITLE
Support for absolute paths

### ISSUE THREAD

**Issue by sergeyzwezdin** [wmonk/create-react-app-typescript#138]
There is **create-react-app** [knwon issue](https://github.com/facebookincubator/create-react-app/issues/741) with supporting absolute paths in application. 

For default react-scripts version based app I ended up with using `.env` file to configure `NODE_PATH`. It works as we need. Details [here](https://github.com/facebookincubator/create-react-app/issues/741#issuecomment-278945308).

If I use same way for `react-scripts-ts` project, `.env` file just ignored here and we're unable to use absolute paths.

Could you please add support of this future for TypeScript version of `create-react-app` utility?

**Comment by wmonk** [comment]
I believe this is a Typescript issue. Please follow #122 discussion. If this is a separate issue please reopen.
