### ISSUE TITLE
Reload doesn't work on file with error when using yarn

### ISSUE THREAD

**Issue by pierre-H** [wmonk/create-react-app-typescript#148]
### Is this a bug report?

yes

### Can you also reproduce the problem with npm 4.x?

yes

### Which terms did you search for in User Guide?

I tried https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-start-doesnt-detect-changes 

### Environment

1. `npm ls react-scripts-ts` (if you haven’t ejected): 2.6.0
2. `node -v`: 8.4.0
3. `npm -v`: 5.3.0
4. `yarn --version` (if you use Yarn): 0.27.5

Then, specify:

1. Operating system: Windows 7 - 32bits

### Steps to Reproduce

(Write your steps here:)

1.  `create-react-app my-app --scripts-version=react-scripts-ts`
2.  `yarn start` in my-app folder

### Expected Behavior

When I edit and save a file which contains a TS error, it should reload automatically.

### Actual Behavior

Nothing.
If I edit another file, it compiles again but the error is still there.

I tried with WebStorm and VS Code. I also followed https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-start-doesnt-detect-changes

### Solution

When I use `npm start` instead of yarn, it works.

Thank you !

**Comment by wmonk** [comment]
Hi, have you got any further with this issue?/

**Comment by pierre-H** [comment]
Very strange : I tried today with yarn, and it's working perfectly !
So I close this issue until I find another useful information ...

**Comment by dmbaranov** [comment]
Have the same issue.. Once I have a typescript error, I need to restart process manually. Tried both with yarn 1.6.0 and npm 6.0

**Comment by SeedyROM** [comment]
@dmbaranov Did you ever find a solution? I'm still experiencing this bug in late December 2018.

**Comment by dmbaranov** [comment]
@SeedyROM no, not really. I don't actually use this project anymore.
