### ISSUE TITLE
Sass Please

### ISSUE THREAD

**Issue by robbyemmert** [wmonk/create-react-app-typescript#155]
Would it be possible to add an option for using sass?

This is the only reason I have to eject at this point. I love where this generator is going. 👍 

Thanks!

**Comment by wmonk** [comment]
Hey, if this lands in `create-react-app` then it will land here too. But until then SASS will not be enabled by default.

**Comment by new-mikha** [comment]
Hi @wmonk , SASS support just been added to `create-react-app`

When it's practical to expect it to land here?
Thanks for your work!

Cheers,
Michael.
