### ISSUE TITLE
Build fails with default tsconfig.json because of recent changes in ts-loader

### ISSUE THREAD

**Issue by pettyalex** [wmonk/create-react-app-typescript#156]
This change here: https://github.com/TypeStrong/ts-loader/pull/621 results in the build failing because it is now using src/src as a root directory instead of src.

If anybody else gets blocked by this, the quick workaround is to change in tsconfig.json

`"rootDir": "src",`
to
`"rootDir": ".",`

To reproduce, just run `create-react-app testing_app --scripts-version=react-scripts-ts` and then run the build, and see:

```
error TS6059: File '/Users/alex.petty/src/testing_app/src/App.test.tsx' is not under 'rootDir' '/Users/alex.petty/src/testing_app/src/src'. 'rootDir' is expected to contain all source files.
```

**Comment by Loilo** [comment]
First and foremost: I'm sorry that my changes broke something.

I can reproduce the error with this package, however, if I try to boil it down I'm not getting the error anymore. I'll try to get to the error over the course of the day, but in case you'd want to help out, take a look at my [repro repo](https://github.com/Loilo/repro-156-create-react-app-typescript) and make a good guess why it's not reproducing the error yet.

**Comment by Loilo** [comment]
Okay, I think I've got it boiled down. I've [opened an issue](https://github.com/TypeStrong/ts-loader/issues/626) over at the `ts-loader` repo to deal with this.

**Comment by Loilo** [comment]
For the record: I've found the issue. Unfortunately, the architectural decisions of my changes were flawed and my tests didn't cover them properly.

I've submitted [a pull request](https://github.com/TypeStrong/ts-loader/pull/627) to the `ts-loader` reverting my changes, a new version fixing the issue should come out later today.

**Comment by Loilo** [comment]
Changes have been reverted in 2.3.6 which was just released. Issue can be closed.

Thanks for your patience.

**Comment by pettyalex** [comment]
Thanks for the prompt fix!

**Comment by johnnyreilly** [comment]
No problem!
