### ISSUE TITLE
How do I disable an ESLint rule? How do I find it's code?

### ISSUE THREAD

**Issue by TomasHubelbauer** [wmonk/create-react-app-typescript#164]
I need to use `any` in a portion of my code because I'm receiving an API response that can have variable shape that is being inspected using reflection.

I have a type like this:

```ts
type Response = {
  id: number;
  title: string;
  customJsonData: any;
}
```

I went to add `// eslint-disable-next-line` over the `customJsonData: any;` but by itself that doesn't do anything. I found [this comment](https://github.com/eslint/eslint/issues/6742#issuecomment-234621402) but I have no idea how to find the ESLint rule name from this output:

```
./src/App.tsx
[17, 15]: Type declaration of 'any' loses type-safety. Consider replacing it with a more precise type, the empty type ('{}'), or suppress this occurence.
```

The suggestion to search for keywords to learn more about each warning is ridiculous, but that may be coming from CRA, I don't know. Either way there is no clear way to tell how what code does a rule I want to temporarily silence have. Can this be fixed in CRA TS or is this a problem in CRA itself?

**Comment by ianschmitz** [comment]
The message you are seeing is from TSLint. You can edit the `tslint.json` file in the root of your project to tweak the TSLint settings to you liking. The linting error your seeing is [no-any](https://palantir.github.io/tslint/rules/no-any/). You can read about the proper comment syntax to disable rules over at https://palantir.github.io/tslint/usage/rule-flags/

**Comment by TomasHubelbauer** [comment]
I used `// tslint:disable-next-line: no-any` to great success. Thank you @ianschmitz

**Comment by ianschmitz** [comment]
If you're using g VS Code I recommend the [TSLint extension](https://marketplace.visualstudio.com/items?itemName=eg2.tslint), which will give you helpful intellisense as well as the ability to add rule flag comments or fix issues with a quick button click

**Comment by TomasHubelbauer** [comment]
Helpful, I do have it, but I was using Insiders and it did not occur to me to install it there as well. Good idea. Thanks!

**Comment by QuantumInformation** [comment]
This tslint line is supposed to be ignored:

![image](https://user-images.githubusercontent.com/216566/33385816-702b49b8-d521-11e7-89b5-09ddda78002c.png)


but it isn't:
![image](https://user-images.githubusercontent.com/216566/33385827-77cd32c6-d521-11e7-9027-16ef59dfe6e3.png)


any ideas?
