### ISSUE TITLE
Changing license to MIT

### ISSUE THREAD

**Issue by Lucasus** [wmonk/create-react-app-typescript#173]
Facebook recently has changed licenses for React and related libraries to MIT (https://github.com/facebookincubator/create-react-app/pull/3189). Have you considered to change the license of your fork to MIT as well?

**Comment by wmonk** [comment]
I guess this will come whenever we merge facebooks latest commits. I don't really have time to do it at the moment.

**Comment by DorianGrey** [comment]
Is MIT since last rebase.
