### ISSUE TITLE
Publish version 2.8.0

### ISSUE THREAD

**Issue by axelhzf** [wmonk/create-react-app-typescript#174]
There is something blocking the publication of the version 2.8.0 ( commit https://github.com/wmonk/create-react-app-typescript/commit/2392778c76a9bb69a74ab1b105f6611749512df9) ?

**Comment by pierre-H** [comment]
ping @wmonk 

@wmonk thank you for your work !

**Comment by wmonk** [comment]
Apologies for the delay, done!

**Comment by pierre-H** [comment]
Thank you !

**Comment by corydeppen** [comment]
@wmonk Will the changelog section of the readme be updated to reflect changes included in the 2.8.0 release?

**Comment by wmonk** [comment]
@corydeppen done
