### ISSUE TITLE
Usage with Enzyme, error: Enzyme expects an adapter

### ISSUE THREAD

**Issue by QuantumInformation** [wmonk/create-react-app-typescript#185]
I have the following setup

![image](https://user-images.githubusercontent.com/216566/32441178-490e0950-c2ee-11e7-8f0a-69fbdba7d69c.png)

but get this error:

```
 Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
          configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
          before using any of Enzyme's top level APIs, where `Adapter` is the adapter
          corresponding to the library currently being tested. For example:

          import Adapter from 'enzyme-adapter-react-15';
```

I get the same error if I rename to `setupTests.ts`

**Comment by adepatie** [comment]
Experiencing the same issue. I've tried changing between "setupFiles" and "setupTestFrameworkScriptFile", using 'require()', 'import * as'. Same error.

**Comment by adepatie** [comment]
@QuantumInformation Fixed my issue by using the answer found here:
https://stackoverflow.com/questions/46435558/could-not-find-declaration-file-for-enzyme-adapter-react-16

**Comment by smacpherson64** [comment]
Similar to @adepatie and the stackoverflow above,

I have a working setup with the following:

**package.json**
```json
...
"enzyme": "^3.0.0",
"enzyme-adapter-react-16": "^1.0.2",
"@types/enzyme": "^3.1.0",
"react-scripts-ts": "2.8.0",
...
```

**setupTests.ts**:
```ts
import * as enzyme from 'enzyme';
import * as Adapter from 'enzyme-adapter-react-16';
enzyme.configure({ adapter: new Adapter() });
```

**Comment by NirBenita** [comment]
Thanks for the workaround people ❤️

I've been having similar problems. It looks like src/setupTests.js is not running before every test file ([as it should](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#srcsetuptestsjs)).

I work around the issue by adding

``` javascript
import * as Adapter from 'enzyme-adapter-react-15';

configure({ adapter: new Adapter() });
```
to the test suite, which works fine for now since it's a small project with not many suites.

**Comment by smacpherson64** [comment]
Hey @nirbenita have you tried renaming that file to setupTests.ts ?

**Comment by wmonk** [comment]
Could someone submit a PR to get this working correctly?

**Comment by ianschmitz** [comment]
`src/setupTests.ts` should be working correctly (is for me on 2.8.0)

**Comment by abenchi** [comment]
It does not work at all for me    
```
"enzyme": "3.2.0",
"enzyme-adapter-react-16": "1.1.0",
"react-scripts-ts": "2.8.0",
```

**Comment by DorianGrey** [comment]
> It does not work at all for me

@abenchi , would you mind elaborating this ? "It does not work" lacks precision.
If you follow these [instructions](https://github.com/DorianGrey/create-react-app-typescript/blob/6277b60b13a2109b22bb96c73ee01b7fba5fc9a1/packages/react-scripts/template/README.md#testing-components) (that's from a PR, but it has only some minor differences from the original version [here](https://github.com/facebookincubator/create-react-app/tree/master/packages/react-scripts/template#testing-components)), what _exactly_ fails to work?

**Comment by DorianGrey** [comment]
Instructions on how to setup `enzyme` have been adopted to conform to the particular typescript requirements.
See [here](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/README.md#testing-components). Yes, it's somewhat hidden, but in the same position as in the original CRA.

**Comment by abenchi** [comment]
Indeed, it was my error, by doing the follwing to avoid the requestAnimationFrame warnings
```
"test": "react-scripts test --env=jsdom --setupTestFrameworkScriptFile=raf/polyfill",
```
I override the setupTests... 
Thanks for your feedback

**Comment by arbtfnf** [comment]
This error occurs when you are using React16, and trying to install Enzyme@2 with "npm i --save-dev enzyme",
Instead use the following code to run Enzyme with React-16
`yarn add enzyme@3.0.0 enzyme-adapter-react-16@1.0.0 raf@3.3.2`

> Here we have to use enzyme@3.0.0 to run it with react16, here we need to install adaptor also. 
So after running this code, inside test folder, create a file( name it eg: setupTest.js ) to wire-up adaptor with enzyme.
In setupTest.js file copy/paste the following:
`import Enzyme from 'enzyme';
import Adaptor from 'enzyme-adaptor-react-16';

Enzyme.configure({
    adaptor: new Adaptor()
});`

Now you need to add jest.config.json file on the root as it, this will tell to run raf then setupTests.js file
`{
    "setupFiles": [
        "raf/polyfill",
        "<rootDir>/src/tests/setupTests.js"
    ]
}`

**Comment by manoharreddyporeddy** [comment]
A simple solution is here:
https://github.com/airbnb/enzyme/issues/1265#issuecomment-388544819

**Comment by quocdai92** [comment]
It is my sample used `create-react-app`
1. I created an application by using `create-react-app`
2. I install `enzyme` and `enzyme-adapter-react-16` by yarn command.
3. After that, I run command `yarn eject`
4. I received a `package.json` file. Inside that, I modify the `jest` property (I add new line 
` "<rootDir>/config/setupTests.js"` in the `"setupFiles"` property.
`"jest": {`
 `       ...`
  `  "setupFiles": [`
  `    "<rootDir>/config/polyfills.js",`
 `     "<rootDir>/config/setupTests.js"`
  `  ]`
`    ...`
`}`
5. After all, I copy `setupTests.js` into folder config.
==>>> It worked!!!
(The setupTests.js you can create with below contents )
`import Enzyme from 'enzyme';`
`import Adapter from 'enzyme-adapter-react-16';`

`Enzyme.configure({ adapter: new Adapter() });`

**Comment by xargr** [comment]
@quocdai92 you save my day.... works for me
```
"jest": {
...
"setupFiles": [
"<rootDir>/config/polyfills.js",
"<rootDir>/src/setupTests.js"
]
```

and inside src folder I put setupTests.js

**Comment by nathanealsp** [comment]
Created project using create-react-app, added Enyzme but go this error

<img width="1668" alt="screen shot 2019-01-15 at 4 22 53 pm" src="https://user-images.githubusercontent.com/25331856/51210884-eaf2ce00-18e1-11e9-8cb8-cc0b16b49268.png">

**setUpTest.js**
```javascript
import { configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });
```

found out that i had a typo changed file to **setupTests.js** and ran `yarn test` again

**package.json**
```javascript
{
  "name": "react_version",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@reach/router": "^1.2.1",
    "react": "^16.7.0-alpha.2",
    "react-dom": "^16.7.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.2",
    "styled-components": "^4.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ],
  "devDependencies": {
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
  }
}
```
