### ISSUE TITLE
Recompiling not always happening after changing code after a  compile error.

### ISSUE THREAD

**Issue by QuantumInformation** [wmonk/create-react-app-typescript#187]
After errors like so, when I change the code, it doesn't force recompiling:
```
Failed to compile
/Users/nikos/d/fooService.ts
(9,29): error TS7006: Parameter 'item' implicitly has an 'any' type.
```
I have to stop and start CRA ts.

**Comment by wmonk** [comment]
Please fill in the issue template.

**Comment by QuantumInformation** [comment]
Maybe start a gitter channel, as some issues are easier to ask someone if they have come across something, than work through a long issue template?

For example, I am trying to run Jest tests and am getting the following.

  console.error node_modules/fbjs/lib/warning.js:33
      Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. http://fb.me/react-polyfills
    console.log console.js:231

But apparently, this has been fixed upstream https://github.com/facebookincubator/create-react-app/issues/3199

**Comment by bootstraponline** [comment]
If it's fixed upstream, then the next release of this repo should contain the fix. I rebased the code recently.

**Comment by QuantumInformation** [comment]
super thx

**Comment by QuantumInformation** [comment]
npm still contains 2.8
