### ISSUE TITLE
Upgrade to TypeScript 2.6.1

### ISSUE THREAD

**Issue by foxylion** [wmonk/create-react-app-typescript#191]
Hi,
with [TypeScript 2.6.1](https://github.com/Microsoft/TypeScript/releases/tag/v2.6.1) available it would be great to update `react-scripts-ts` to the latest version.
This would give us some new features: https://blogs.msdn.microsoft.com/typescript/2017/10/31/announcing-typescript-2-6/

**Comment by bootstraponline** [comment]
will be in the next release 😄 

https://github.com/wmonk/create-react-app-typescript/blob/bdc024db5fdceffd00214f9245c92859b540c245/packages/react-scripts/package.json#L58

**Comment by ianschmitz** [comment]
Related: #181

**Comment by gyzerok** [comment]
Should this be closed now @foxylion?

**Comment by foxylion** [comment]
Yes, thanks you!

**Comment by olegskl** [comment]
Is 2.9.0 not ready for release yet? Anything we can do to help?

**Comment by Hotell** [comment]
any updates on 2.9.0 ?

**Comment by bootstraponline** [comment]
still waiting on upstream to publish a new release https://github.com/facebookincubator/create-react-app/releases

**Comment by salehe** [comment]
I wonder what happened to the commit that upgraded typescript! It is nowhere to be found on the master tree.

**Comment by bootstraponline** [comment]
there have been [over 100 commits to upstream since `v1.0.17`](https://github.com/facebookincubator/create-react-app/releases) and no new release.

i think we're still waiting for upstream to release before syncing the latest changes.

**Comment by wmonk** [comment]
@salehe @bootstraponline please see #221

**Comment by salehe** [comment]
2.11 is still on 2.5.3 but I see you made PR https://github.com/wmonk/create-react-app-typescript/pull/225
👍

**Comment by olegskl** [comment]
I'm not sure why the wait for upstream is necessary for a TypeScript update 😕

**Comment by wmonk** [comment]
TS@2.6.2 is released in react-scripts-ts@2.12.0
