### ISSUE TITLE
Way to remove data-test attributes for prod?

### ISSUE THREAD

**Issue by QuantumInformation** [wmonk/create-react-app-typescript#195]
What would need to be done to remove data-test attributes for prod? These are useful for testing.

For inspiration see https://github.com/oliviertassinari/babel-plugin-react-remove-properties

**Comment by bootstraponline** [comment]
I'm keeping the data-test attributes because otherwise there's no way to test prod. Probably a customization like this belongs in a fork since there's no way to serve both use cases. It'd also make the pipeline slower for people who don't need to remove attributes.

**Comment by DorianGrey** [comment]
I agree with @bootstraponline - this is out of scope for this fork, and we don't want to diverge too much from the original CRA.
