### ISSUE TITLE
Error when running npm run build

### ISSUE THREAD

**Issue by statto1974** [wmonk/create-react-app-typescript#20]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Can you reproduce the problem with latest npm?

Yes

### Description

An error when running `npm run build`

### Expected behavior

Runs successfully

### Actual behavior

```
C:\Apps\insite\node_modules\react-scripts-ts\scripts\build.js:32
var { highlight } = require('cli-highlight');
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933:3
```

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts-ts` (if you haven’t ejected): react-scripts-ts@1.0.6
2. `node -v`: v5.8.0
3. `npm -v`: 4.1.2

Then, specify:

1. Operating system: Windows 10
2. Browser and version: Chrome

**Comment by wmonk** [comment]
That's weird I thought object destructuring was covered in node 5

**Comment by wmonk** [comment]
I guess not, I will happily accept a PR to get this working back to node4

**Comment by dbus0** [comment]
Any update on this? It prevents any kind of deployment.

If you can show me exactly where and what needs to be done I'll fix it, but I don't know enough to do it myself (I use create-react-app to avoid having these issues).

**Comment by statto1974** [comment]
I was able to upgrade to the latest version of nodejs and that fixed it.

**Comment by wmonk** [comment]
@dbus0 the issue is that node4 does not support destructuring like:
```
const { highlight } = require('highlight');
```

Instead it should be:
```
const highlight = require('highlight').highlight;
```

For a quick fix I would upgrade your node version, as node4 will be leaving it's LTS period in a few months. Node 6 will support this package fine.

**Comment by wmonk** [comment]
@dbus0 @statto1974 in fact, node 5 has no LTS, so I would recommend 6.

**Comment by wcandillon** [comment]
@wmonk any change to have node v5 support?

**Comment by wmonk** [comment]
@wcandillon please see above, and [here](https://github.com/nodejs/LTS). Node 5 is no longer supported, I would recommend upgrading to 6.

![](https://raw.githubusercontent.com/nodejs/LTS/master/schedule.png)
