### ISSUE TITLE
git-tags for npm releases

### ISSUE THREAD

**Issue by pulse00** [wmonk/create-react-app-typescript#200]
Would it be possible to create tags for each release? It would make it easier to track changes if one wants to maintain a fork of this fork :)

Anyway, great project, thanks!

**Comment by asfernandes** [comment]
Please, create tags for the releases.

**Comment by wmonk** [comment]
Sure, will do in the next release. Regarding your fork, I am planning on breaking the repo away from the facebook fork to just maintain the `react-script-ts` package. This will be a breaking change for your fork.
