### ISSUE TITLE
Jest Ignoring Babelrc

### ISSUE THREAD

**Issue by mchandler-cng** [wmonk/create-react-app-typescript#211]
I am attempting to use `babel-plugin-emotion` with a freshly created cra-typescript app. I have successfully injected the plugin into the webpack config using a method similar to the one found [here](https://gist.github.com/mrlundis/ca809eea890fa9fd5d98facd51cde731) with `react-app-rewired` so the plugin works fine with `build` and `start`, but now my problem is that I cannot get Jest to pay attention to the fact that the emotion plugin is listed in `.babelrc`. When I run my tests, I get errors identical to those you'd get if the plugin was not loaded in webpack (`TypeError: react_emotion_1.default.div is not a function`, if it matters).

I've tried inserting `jest->globals->ts-jest->useBabelrc: true` in package.json and have also overridden the config using `react-app-rewired` to no effect.

I've dug through the source of `react-scripts` in this repo but I'm having trouble understand what is ultimately responsible for setting up Jest, so I'm not sure if this is a concern of `create-react-app-typescript` or `ts-jest` or something else entirely, so if someone could point me in the right direction, I'd really appreciate it.

**Comment by Nunnery** [comment]
[createJestConfig.js](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/scripts/utils/createJestConfig.js) is ultimately responsible for setting up the Jest config. You could add the ```useBabelrc``` value in the section containing [L61-63](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/scripts/utils/createJestConfig.js#L61-L63).

**Comment by mchandler-cng** [comment]
Thanks @Nunnery
