### ISSUE TITLE
Option to use tslint.json from parent directory

### ISSUE THREAD

**Issue by stephtr** [wmonk/create-react-app-typescript#215]
#### Is this a bug report?
No

Currently I have a project with multiple react-apps in subfolders and would like to share the `tslint.json` file across them (without having files which only contain the extend property).
At the moment it isn't possible because the path of `tslint.json` is fixed in [paths.js#L62](https://github.com/wmonk/create-react-app-typescript/blob/e404a66e936095a9c65f9995c84e9f4f7efbc194/packages/react-scripts/config/paths.js#L62) to each app.
Wouldn't it be better to check the parent directories if the file doesn't exist in the app's root folder?

**Comment by wmonk** [comment]
You should be able to use [extends](https://palantir.github.io/tslint/usage/configuration/).

**Comment by stephtr** [comment]
That's what I was using, but looking in the parent directories would have the advantage of reducing the number of files if one has a few different react projects in different subdirectories.

However that scenario is probably to specific.
