### ISSUE TITLE
Can I use JS and TS?

### ISSUE THREAD

**Issue by gperdomor** [wmonk/create-react-app-typescript#217]
Hi... I want start the migration of a large app to TS.

Can I use ported typescript files and unported js files at the same time?

If not, exist any unofficial way to do that?

**Comment by tpetrina** [comment]
Yes, you can. Follow this guide in https://github.com/Microsoft/TypeScript-React-Starter/issues/91.

**Comment by kandros** [comment]
I've done this the past week, without ejecting
https://stackoverflow.com/questions/47508564/migrating-create-react-app-from-javascript-to-typescript

**Comment by nickmccurdy** [comment]
Looks like this can be closed.

**Comment by r3nya** [comment]
Hey @gperdomor!
Please close this issue.
