### ISSUE TITLE
Could not find custom rule directory

### ISSUE THREAD

**Issue by kamek-pf** [wmonk/create-react-app-typescript#219]
As of today, fresh projects are unable to build.
```sh
yarn create react-app test-app --scripts-version=react-scripts-ts
cd test-app
yarn start

...

Failed to compile.

./src/index.tsx
Module build failed: FatalError: Could not find custom rule directory:
```
Everything was fine yesterday, today none of my co workers are able to start new projects.
I assume an upstream change broke something here, any idea what should be done ?

**Comment by wmonk** [comment]
This seems to be an issue of `tslint`, introduced in https://github.com/palantir/tslint/pull/3640 as far as I can tell. Do you have anything in your tslint.json related to this?
