### ISSUE TITLE
newly created app does run tests

### ISSUE THREAD

**Issue by arolson101** [wmonk/create-react-app-typescript#222]
### Is this a bug report?

yes

### Can you also reproduce the problem with npm 4.x?

yes

### Which terms did you search for in User Guide?

(Write your answer here if relevant.)

### Environment

1. `node -v`: v9.1.0
2. `npm -v`: 4.6.1
3. `yarn --version` (if you use Yarn): 1.3.2
4. `npm ls react-scripts-ts` (if you haven’t ejected): react-scripts-ts@2.8.0

Then, specify:

1. Operating system: windows 10
2. Browser and version (if relevant):

### Steps to Reproduce

(Write your steps here:)

1. create-react-app my-app --scripts-version=react-scripts-ts
2. cd my-app/
3. introduce an error in App.test.tsx
4. npm test

### Expected Behavior

I expect that it will run the tests and display an error message

### Actual Behavior

No tests were run, even when forcing it to run all tests.  E.g.:
```
PS C:\crap> npm test

> crap@0.1.0 test C:\crap
> react-scripts-ts test --env=jsdom

No tests found related to files changed since last commit.
Press `a` to run all tests, or run Jest with `--watchAll`.

Watch Usage
 › Press a to run all tests.
 › Press p to filter by a filename regex pattern.
 › Press t to filter by a test name regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
No tests found
In C:\crap
  16360 files checked.
  testMatch: C:\crap\src\**\__tests__\**\*.ts?(x),C:\crap\src\**\?(*.)(spec|test).ts?(x) - 1 match
  testPathIgnorePatterns: \\node_modules\\ - 16360 matches
Pattern: "" - 0 matches

Watch Usage: Press w to show more.
```

### Reproducible Demo

https://github.com/arolson101/crap

**Comment by DorianGrey** [comment]
Hm... checked this for both `npm` and `yarn` on linux, and everything works fine. Seems to be a windows-specific problem.

**Comment by mikew** [comment]
Note the message "No tests found related to files changed since last commit" actually means since last git commit. So if typing `git status` in a terminal shows no changed files then no tests will run.

If you press `a` at that prompt to run all tests is it run then?

**Comment by arolson101** [comment]
@mikew yes, I pressed a in that example.  And I made a local edit with a syntax error.
@DorianGrey I tested on macOS and it works fine there, too.  Can anyone else with windows confirm?

**Comment by DorianGrey** [comment]
Checked that repo on Windows 10, and everything seems to work as expected ...

Started using `npm test`, and introduced some changes regarding semantics and syntax - both triggered the watch correctly and resulted in failed tests (see below).

Semantic error:
```
src\App.test.tsx
  ● renders without crashing

    expect(function).toThrow(undefined)

    Expected the function to throw an error.
    But it didn't throw anything.

      at Object.<anonymous> (src/App.test.tsx:7:45)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  × renders without crashing (148ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.502s, estimated 3s
Ran all test suites related to changed files.
```
Syntax error:
```
src\App.test.tsx
  ● Test suite failed to run

    D:/Workspaces/crap/src/App.test.tsx: Unexpected token (9:4)
         7 |     var div = document.createElement('div');
         8 |     expect(function () { return ReactDOM.render(React.createElement(App_1.default, null), div); }).
      >  9 |     ;
           |     ^
        10 | });
        11 | //# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQXBwLnRlc3QuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJBcHAudGVzdC50c3giXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7QUFBQSw2QkFBK0I7QUFDL0Isb0NBQXNDO0FBQ3RDLDZCQUF3QjtBQUV4QixFQUFFLENBQUMsMEJBQTBCLEVBQUU7SUFDN0IsSUFBTSxHQUFHLEdBQUcsUUFBUSxDQUFDLGFBQWEsQ0FBQyxLQUFLLENBQUMsQ0FBQztJQUMxQyxNQUFNLENBQUMsY0FBTSxPQUFBLFFBQVEsQ0FBQyxNQUFNLENBQUMsb0JBQUMsYUFBRyxPQUFHLEVBQUUsR0FBRyxDQUFDLEVBQTdCLENBQTZCLENBQUM7UUFDN0MsQUFEOEMsSkFBQSxDQUFBO0FBQzlDLENBQUMsQ0FBQyxDQUFDIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0ICogYXMgUmVhY3QgZnJvbSAncmVhY3QnO1xyXG5pbXBvcnQgKiBhcyBSZWFjdERPTSBmcm9tICdyZWFjdC1kb20nO1xyXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwJztcclxuXHJcbml0KCdyZW5kZXJzIHdpdGhvdXQgY3Jhc2hpbmcnLCAoKSA9PiB7XHJcbiAgY29uc3QgZGl2ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZGl2Jyk7XHJcbiAgZXhwZWN0KCgpID0+IFJlYWN0RE9NLnJlbmRlcig8QXBwIC8+LCBkaXYpKS5cclxufSk7XHJcbiJdfQ==

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.315s, estimated 1s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```

**Comment by arolson101** [comment]
whatever was wrong before seems to be ok now.
thanks for your help, all!

**Comment by laere** [comment]
I was having this issue as well.

I added --watchAll to my test script and it allowed me to see all of my tests within .test.js files.

My script: "test": "react-scripts test --colors --watchAll"

Hope this helps someone in the future.
