### ISSUE TITLE
Updating Files Does not Cause HMR Reload

### ISSUE THREAD

**Issue by mchenryc** [wmonk/create-react-app-typescript#224]
I encountered https://github.com/facebookincubator/create-react-app/issues/659 (bug has same title), which has multiple known causes. The cause in my case was not listed, but has already been fixed upstream.

The issue was that my app was nested beneath the folder named* `$monorepo/packages/node_modules`, and ignored by webpack-dev-server's watch, due to an overeager regex for `watchOptions.ignored`.

This has already been fixed in CRA and master (1e98d0f428fd72f0a700b0c096b0d1a9e717d7ec, 36cd35d684f6f0eda971b30c789010758fc61ceb), but is not yet in the released`react-scripts-ts`.

This issue should be closed by the next release. Perhaps this will help others.

\* I'm using the ["Alle" monorepo](https://github.com/boennemann/alle) model, similar to Lerna, [adopted by PouchDB](https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4)

**Comment by mchenryc** [comment]
Correction, this has not yet been fixed upstream. I'm not yet sure why I saw the watch being triggered when using that patch - it may relate to https://github.com/webpack/webpack-dev-server/issues/1208, though would not explain sporadic success.

**Comment by wmonk** [comment]
Ok, can we close this and wait for it to be fixed upstream? `react-scripts-ts@2.12.0` is now up to date with `react-scripts@1.0.17`, and there hasn't been a change for a while.

**Comment by mchenryc** [comment]
Agreed, a divergence for this issue would be silly. Please close.

**Comment by mchenryc** [comment]
@wmonk Just an update - I notice _many_ changes just became available upstream today (https://github.com/facebookincubator/create-react-app/blob/master/CHANGELOG.md)

**Comment by wmonk** [comment]
@mchenryc lol I waited ages and then just decided to update to 17. Thanks for the heads up, better get to work!
