### ISSUE TITLE
jest is ignoring JS and JSX files.

### ISSUE THREAD

**Issue by kresli** [wmonk/create-react-app-typescript#230]
This is more a question then a bug report.
Any ".js" or ".jsx" are ignored by tests, however those are acceptable on dev or prod environment. Is this by design or it is a bug? 
[createJestConfig.js](https://github.com/facebookincubator/create-react-app/blob/next/packages/react-scripts/scripts/utils/createJestConfig.js)

example: rename `App.test.tsx` to `App.test.jsx`
compile error: 
```
No tests found
In /Documents/create-react-app-typescript
  12 files checked.
  testMatch: /Documents/create-react-app-typescript/src/**/__tests__/**/*.ts?(x),/Documents/create-react-app-typescript/src/**/?(*.)(spec|test).ts?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 12 matches
Pattern: "" - 0 matches

```

Thanks

**Comment by bootstraponline** [comment]
It seems like we should support both.
