### ISSUE TITLE
Scaffolded app includes additional .js files

### ISSUE THREAD

**Issue by hdra** [wmonk/create-react-app-typescript#236]
Not sure if this should go here or [here](https://github.com/Microsoft/TypeScript-React-Starter/), but the freshly scaffolded react app seems to include additional `index.js` and `registerServiceWorker.js` file in its `src/` directory. 

They don't cause any issue, and can be simply deleted, but I don't see any reason for them to be there either. 

### Is this a bug report?

Probably

### Environment

1. `npm ls react-scripts-ts` (if you haven’t ejected): 2.13.0
2. `node -v`: 8.9.4
3. `npm -v`: 5.4.2
4. `yarn --version` (if you use Yarn): 1.3.2

Then, specify:

1. Operating system: macOS 10.13.2

### Steps to Reproduce

1. `create-react-app test-scaffold --scripts-version=react-scripts-ts`

### Expected Behavior

`tree test-scaffold/src` outputs:

```
test-scaffold/src
├── App.css
├── App.test.tsx
├── App.tsx
├── index.css
├── index.tsx
├── logo.svg
└── registerServiceWorker.ts

0 directories, 7 files
````

### Actual Behavior

`tree test-scaffold/src` outputs:

```
test-scaffold/src
├── App.css
├── App.test.tsx
├── App.tsx
├── index.css
├── index.js
├── index.tsx
├── logo.svg
├── registerServiceWorker.js
└── registerServiceWorker.ts

0 directories, 9 files
```

**Comment by DorianGrey** [comment]
Removed via #237. Seems like they remained there after merging with upstream ...
