### ISSUE TITLE
Is the documentation for adding CSS files from node_modules (using TypeScript) correct?

### ISSUE THREAD

**Issue by dccarmo** [wmonk/create-react-app-typescript#247]
According to the [User Guide](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/README.md#adding-bootstrap), you can import CSS files from node_modules like this: 

`import 'bootstrap/dist/css/bootstrap.css';`

But I can't make that work, and I'm assuming the docs for TypeScript requires a bit more setup so`tsc` can compile properly. Right now I'm getting this error:

`Module not found: Can't resolve 'bulma/bulma.css' in '/Users/.../src'`

What is the correct way of making TypeScript and Webpack play along nicely in this case without ejecting?

**Comment by ianschmitz** [comment]
Can you try using require instead?

```js
require('bootstrap/dist/css/bootstrap.css')
```

I know i've had issues with images following the create-react-app user guide, but using require works just fine.

**Comment by dccarmo** [comment]
That worked! But only after I reset the watcher. After that, even `import` is working. 

Weird, but well, it's working now. 

Thanks!

**Comment by matthewberryman** [comment]
require isn't working for me. What's the 'nice' solution here? I could use webpack although that seems like a lot of work, or manually copying the css over and referencing (but then when I update bootstrap I need to manually copy them back over)

**Comment by matthewberryman** [comment]
sorry, my bad, the instructions I was following had  a `import 'bootstrap/dist/css/bootstrap-theme.css';` and on checking the latest bootstrap I'm using that doesn't exist any more. Removing that line and leaving `
import 'bootstrap/dist/css/bootstrap.css';` successfully imports that. :)
