### ISSUE TITLE
Update uglifyjs-webpack-plugin to support prod builds with es6 target or higher

### ISSUE THREAD

**Issue by thetric** [wmonk/create-react-app-typescript#248]
The `react-scripts` package uses the UglifyJsPlugin version distributed by webpack (`webpack.optimize.UglifyJsPlugin`) which is quite old and doesn't support the minification of ES6 code (see [here](https://github.com/wmonk/create-react-app-typescript/blob/7149b3796c1c2d08606eb1656b628fc69cac7f3f/packages/react-scripts/config/webpack.config.prod.js#L287)).
Since [version 1.0.0](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/CHANGELOG.md#100-2017-10-23) the plugin (now under a separate repo) uses a new uglify version that supports ES6 minification. Similar projects like angular-cli are already using it (https://github.com/angular/angular-cli/pull/7610) or are planning to use it (create-react-app in [2.0.0](https://github.com/facebook/create-react-app/issues/3815)) .

Simply replacing the old plugin with [the new one](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#uglifyjs-webpack-plugin) would actually resolve #158 and #21 and bring ES6 prod builds!  :rocket:

**Comment by joshfarrant** [comment]
Thanks for this @thetric! Any info on when to expect a release?

**Comment by thetric** [comment]
Closed in 39d6c62

**Comment by johannestroeger** [comment]
could this be publish?

**Comment by thetric** [comment]
Looks like an Angular CLI issue. I guess you have mixed up the repos: https://github.com/angular/angular-cli/issues/7799#issuecomment-389206753
