### ISSUE TITLE
.mjs support

### ISSUE THREAD

**Issue by savovs** [wmonk/create-react-app-typescript#259]
Hi guys, any chance [this PR](https://github.com/facebook/create-react-app/pull/3239) will make its way in sometime soon?

**Comment by mbrowne** [comment]
There is indeed an issue with .mjs files...the latest release candidate version of [apollo-client](https://github.com/apollographql/apollo-client) (2.1.0-rc.1), which now uses .mjs files if the version of node supports it, is now broken when using create-react-app-typescript. But it appears that the above PR was already merged, so there must be some other issue. In the case of apollo-client, it can be resolved in the meantime by removing all mentions of .mjs from webpack.config.dev.js (Apollo then falls back to the .js files), but obviously this is not ideal...

**Comment by mbrowne** [comment]
The react-apollo issue appears to be solved:
https://github.com/apollographql/react-apollo/issues/1750

**Comment by mbrowne** [comment]
Related: https://github.com/wmonk/create-react-app-typescript/issues/287. I think this issue can be closed; once #287 is fixed then .mjs files should be working well across the board.

**Comment by DorianGrey** [comment]
Was already fixed in 2.15.1 .
