### ISSUE TITLE
Unnecessary semicolon issue

### ISSUE THREAD

**Issue by farzadmf** [wmonk/create-react-app-typescript#263]
Hi,

I'm having an issue with class-level arrow functions, e.g.:

```typescript
class MyComponent extends React.Component<...> {
  doSomthing = () => {
    /* ... */
  }
}
```

I'm also using VSCode and prettier extension. When I run the *Format Document* command in VSCode, it seems that prettier is doing the formatting (or another extension), but this arrow function will end up having a semicolon at the end:

```typescript
class MyComponent extends React.Component<...> {
  doSomthing = () => {
    /* ... */
  };
}
```

VSCode highlights this semicolon as an error, and when I run my application, it's complaining about `Unnecessary semicolon`.

Looking at tslint repo, I tried to change the behavior by changing my `tslint.json` to this:

```json
"rules": {
    "semicolon": [true, "always", "ignore-bound-class-methods"],
}
```

After doing that, my VSCode editor no longer sees the semicolon as an error, but I still get the `Unnecessary semicolon` when running the application

**Comment by farzadmf** [comment]
Thank you @AidanGG for your answer. One question: how can I customize the formatting in VSCode? For example, when to beak the arguments so that each one is on a separate line, and things like that?

**Comment by farzadmf** [comment]
As it turns out, I misunderstood @AidanGG 's answer: the content there should be all the content of `tslint.json`; what I was doing was to change only the `extends` section, and leave everything there as is. Closing now as it seems to be working :)

**Comment by JohnYoungers** [comment]
Alternatively, you can update this rule in your tslint file:

```
"semicolon": [true, "always", "ignore-bound-class-methods"]
```
