### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by pmoleri** [wmonk/create-react-app-typescript#264]
### Is this a bug report?

No

There's an [improvement in react-scripts](https://github.com/facebook/create-react-app/commit/b43ad04b880f460ed23dbb7968bae634bf7dbc91) that I want to merge here.

I don't know what's the best workflow to contribute to this project. If we just make PR's for individual changes, or there's a process to merge CRA changes in batches, so both projects maintain a certain parity.

Thanks.

**Comment by DorianGrey** [comment]
There are roughly two categories of changes:
- Changes that have been made in CRA: Those are intended to be merged as one for each released version of CRA. Always accepting PRs for these if we (obviously) don't have time to merge shortly.
- Changes that refer to CRA-ts exclusively: Always accepting PRs for this.

**Comment by pmoleri** [comment]
Great. So, just to clarify. It wouldn't make sense to merge this individual commit from CRA-next.
We wait for it to land in master and then merge the whole branch in a single PR?

**Comment by DorianGrey** [comment]
Yes, once this gets released, i.e. it's most useful to merge from commits that set up a new release.
