### ISSUE TITLE
Configure tslint severity per rule

### ISSUE THREAD

**Issue by ackvf** [wmonk/create-react-app-typescript#273]
I have installed a new project and turned on `"semicolon": [true, "never"]`, now I need to remove semicolons in every file in the project as the app fails with compiler error.

For now, I set `"defaultSeverity": "warning",` in tslint.json, but I would like to enforce other rules more strictly.

Wouldn't it be nice if tslint allowed setting a severity of a rule in a similar way as [eslint does](https://eslint.org/docs/rules/semi)?

**Comment by fruitraccoon** [comment]
@ackvf You can specify a specific severity on each rule in `tslint.json` - from [the docs](https://palantir.github.io/tslint/usage/configuration/):

> Each rule is associated with an object containing:
> - options?: any: An array of values that are specific to a rule.
> - severity?: "default" | "error" | "warning" | "off": Severity level. Level “error” will cause exit code 2.

What I have in my config is `defaultSeverity` of `error` (the default) and then relax specific rules to warnings. For example: `"no-debugger": { "severity": "warning" },`

Hope this helps.

**Comment by ackvf** [comment]
Thank you. I missed that in the docs.
