### ISSUE TITLE
TS aliases are not recognized in tests

### ISSUE THREAD

**Issue by farzadmf** [wmonk/create-react-app-typescript#279]
Hi,

I'm using aliases in my `tsconfig.json`; something like this

```json
  // ...
  "baseUrl": "./",
  "paths": {
    "Common/*": ["src/common/*"],
    "Components/*": ["src/components/*"],
    "Containers/*": ["src/containers/*"],
    "Store/*": ["src/store/*"]
  }
```

But when I run the tests, I see error messages regarding `Cannot find module ...`, which is pointing to the aliases I'm using in the code

Can you please help we with this regard? I saw an issue talking about a similar thing, but I don't think I saw aliases being mentioned there.

Thank you in advance

**Comment by nnyegaard** [comment]
I think you also need to setup aliases in webpack, and to do that you need to eject.

**Comment by farzadmf** [comment]
The thing is that I prefer not to eject the application

**Comment by nnyegaard** [comment]
I don't think it's possible.

**Comment by farzadmf** [comment]
You're right @untsamphan , thank you
