### ISSUE TITLE
Migrate create-react-app app to create-react-app-typescript guide?

### ISSUE THREAD

**Issue by bstro** [wmonk/create-react-app-typescript#28]
Is there any easy way to convert an existing `create-react-app` application over to using `create-react-app-typescript`? Its not super clear to me how to accomplish but I suspect it would be easy.

**Comment by wmonk** [comment]
Hey @bstro, i've personally not tried, but theoretically it should be as easy as swapping `react-script` in your `npm scripts` with `react-scripts-ts`.

**Comment by wmonk** [comment]
Hey @bstro I am going to close this issue. If you fancy writing up your experience of switching, then I will happily accept a PR from you!

**Comment by galvanu** [comment]
Did anyone tried to do this migration and has any insights?

**Comment by disaacson** [comment]
In case anyone else finds this issue through Google, @galvanu wrote a [great quick guide](https://stackoverflow.com/questions/47508564/migrating-create-react-app-from-javascript-to-typescript) that worked for me. Also see the discussion in #108.
