### ISSUE TITLE
Getting editor (Atom) to show lint rule violations.

### ISSUE THREAD

**Issue by erikh2000** [wmonk/create-react-app-typescript#285]
I would like my editor to show the same linting rules as the build uses. Using a fresh app with no post-creation changes made, I followed the directions here ( https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/README.md#displaying-lint-output-in-the-editor ). (ESLint plugin installed, add/edit `.eslintrc`)

It doesn't work. No linting indicators are shown in the editor.

Those instructions DO work for me for a standard create-react-app (not typescript-based) app. So this confirms that a linter is installed and working in my editor.

I tried also changing the `extends` value to `tslint-react`, `tslint.json`, `./tslint.json`. No change in results. Although certainly I'm no expert on the correct syntax to set this. It seems like since the rules are overridden in `tslint.json`, that the `.eslintrc` must somehow refer to `tslint.json` to pick up those overrides.

Has anyone got linting working in Atom? What is your setup?

Atom/eslint/create-react-app versions are all the newest since yesterday, 3/24/18. Will post versions or debug info if anyone believes it is helpful.

**Comment by wmonk** [comment]
Please fill the issue template correctly.
