### ISSUE TITLE
.mjs files in node_modules break jest

### ISSUE THREAD

**Issue by mbrowne** [wmonk/create-react-app-typescript#287]
### Is this a bug report?

Yes

### Can you also reproduce the problem with npm 4.x?

Yes

### Environment

All environments

### Steps to Reproduce

1. `yarn add graphql@0.13.2 @types/graphql`
1. Add the following code to App.tsx:

        import { graphql } from 'graphql'
        console.log(graphql)

1. `yarn test -t 'renders without crashing'`

### Expected Behavior

Test should pass

### Actual Behavior

     FAIL  src/App.test.tsx
      ● Test suite failed to run

        /Users/mbrowne/_temp/test-app/node_modules/graphql/index.mjs:2
        export { graphql, graphqlSync } from './graphql';
        ^^^^^^

        SyntaxError: Unexpected token export

### Solution

This is a known bug in create-react-app. The fix should be simple: simply merge [this PR](https://github.com/facebook/create-react-app/pull/4085) into this repo (it was already merged into the official create-react-app).

**Comment by gaearon** [comment]
If your project is built with Create React App and not ejected, `react-scripts@1.1.2` should fix this.
Here is how to upgrade:

https://github.com/facebook/create-react-app/releases/tag/v1.1.2

Otherwise you can apply a [similar fix](https://github.com/facebook/create-react-app/pull/4085/files) yourself in your project config. Cheers!

**Comment by mbrowne** [comment]
@gaearon this still needs to be fixed in react-scripts-ts. It doesn't make sense to use the official version of react-scripts as all the important functionality of this repo is provided by react-scripts-ts. But yes, you can alternatively eject and then apply that fix manually.

**Comment by mbrowne** [comment]
It looks like currently, .mjs files are actually included twice in the array in react-scripts-ts (at the beginning and at the end):
https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/scripts/utils/createJestConfig.js#L50

Maybe the result of a bad merge?
