### ISSUE TITLE
Debugging Tests

### ISSUE THREAD

**Issue by morsh** [wmonk/create-react-app-typescript#29]
Hi,
I'd like to debug tests by running:
`
yarn test --debug
`

I see that it already supported in:
https://github.com/facebookincubator/create-react-app/pull/1360

Would have been nice to add this here as well.

**Comment by heyimalex** [comment]
That doesn't look like it's been merged? It probably won't be working here until it lands upstream.

**Comment by morsh** [comment]
Sure - And great work on this repo, it's SUPER useful!

**Comment by heyimalex** [comment]
All credit goes to @wmonk! I just drop in on issues sometimes 😃

**Comment by wmonk** [comment]
@heyimalex thanks for triaging! @morsh gonna close this as it'll be merged once landed in fb/create-react-app
