### ISSUE TITLE
React.createRef() doesn't exist in v16.3.1

### ISSUE THREAD

**Issue by celikmus** [wmonk/create-react-app-typescript#293]
### Is this a bug report?
Yes

### Can you also reproduce the problem with npm 4.x?
n/a, used create-react-app.

### Which terms did you search for in User Guide?
createRef

### Environment
create-react-app <my-app> --scripts-version=react-scripts-ts

### Steps to Reproduce
React.createRef() type has not been implemented; it has been as part of React @v16.3.0.
I created a new app with create-react-app with the command line provided above, and received the @type/react v16.3.1, which doesn't have React.createRef().

### Expected Behavior
React.createRef() should have a TypeScript interface, perhaps something like below:

interface React {
  createRef<T>(): React.Ref<T>;
}

### Actual Behavior
createRef() can not be found in React interface.

### Reproducible Demo
n/a

**Comment by DorianGrey** [comment]
This is not a problem of this setup, but of `@types/react`, which seems to not have been updated yet. There already is a PR pending on the `DefinitelyTyped` repo: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24624
You will have to wait for this to land before being able to use these new functions from `typescript` (or use your own augmentation for until then).

**Comment by raheelll** [comment]
When Feature will stable in Latest version?. Please confirm.
