### ISSUE TITLE
npm run build hangs

### ISSUE THREAD

**Issue by VolleMelk** [wmonk/create-react-app-typescript#294]
Hi,

So I've created a react app using `create-react-app [...]` (which works like a charm). Developing and building on my machine works perfectly.

I just can't get the thing to build inside a Windows docker container. Most likely I'm missing some libraries, files or installations.. But I can't seem to figure out how to debug this.

`npm start` and `npm run build` both hang at the same time:

```powershell
PS K:\> npm start

> rws.omg-app@0.1.0 start K:\
> react-scripts-ts start

Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
Watching: K:\src
Starting the development server...

No valid rules have been specified
# Hangs, aborting using CTRL+C

Terminate batch job (Y/N)? Y
PS K:\> npm run build

> rws.omg-app@0.1.0 build K:\
> react-scripts-ts build

Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
No valid rules have been specified
# Hangs, aborting using CTRL+C
Terminate batch job (Y/N)? Y
PS K:\>
```

I've reset my `tslint.json` file which explains the 'No valid rules have been specified' error, I'm able to reproduce the hanging builds using a pristine React application created with `create-react-app`.

So: I need more logging, how to enable this? I thought it wasn't fair to label this as a bug, since it's working fine on my own machine.

**Comment by wmonk** [comment]
Please fill the template

**Comment by VolleMelk** [comment]
That's a bit harsh. Did you even get to the question mark?

**Comment by VolleMelk** [comment]
Nevermind, found it

**Comment by DenisBiondic** [comment]
@VolleMelk what was the solution in the your case?

**Comment by phillx** [comment]
@DenisBiondic @VolleMelk  I'd like to know..

**Comment by VolleMelk** [comment]
Sorry, I didn't fill out the template
