### ISSUE TITLE
create-react-app target broken

### ISSUE THREAD

**Issue by gottfired** [wmonk/create-react-app-typescript#304]
### Is this a bug report?

Yes

### Steps to Reproduce

1. run yarn create-react-app in root. The target in package.json references cra.sh which doesn't exist. It was rewritten to cra.js

Broke during this commit: https://github.com/wmonk/create-react-app-typescript/commit/7db4c43ea1d10080d2864a091482a6a476ee2be7. This reverted a lot back to old settings: node version, lerna version, npm/yarn, postinstall, publish steps, etc.

**Comment by wmonk** [comment]
I think this will be fixed in #302
