### ISSUE TITLE
Map tsconfig "paths" to Jest config.

### ISSUE THREAD

**Issue by StevenTCramer** [wmonk/create-react-app-typescript#31]
in my `tsconfig` file I have 

```
    "paths": {
      "shared/*":["src/shared/*"]
    }
```
jest will not use this.  But to fix jest I only need to update the `utils\createJestConfig.js` as 

```
    moduleNameMapper: {
      '^react-native$': 'react-native-web',
      'shared/(.*)':'<rootDir>/src/shared/$1'
    },
```
could we automate the conversion so one would not have to eject to do this?

**Comment by wmonk** [comment]
Not 100% sure what the issue is here. Will happily accept a PR to fix this though.
