### ISSUE TITLE
Enable webpack hot reload?

### ISSUE THREAD

**Issue by jokester** [wmonk/create-react-app-typescript#310]
I was able to get it work in https://github.com/jokester/typescript-boilerplate/commit/92df62e22149a784277a225877a2e8cc5f674ed3

Can I PR it? (not confident to say it's optimal though: HMR is mysterious to me)

**Comment by jokester** [comment]
see #312

**Comment by DorianGrey** [comment]
See the [comment](https://github.com/wmonk/create-react-app-typescript/pull/312#issuecomment-387974687) on the PR.
