### ISSUE TITLE
ES6 import for svg not working but require works

### ISSUE THREAD

**Issue by jeremistadler** [wmonk/create-react-app-typescript#32]
### Description

I'm trying to import svg images with the following code: 

```javascript
import food from './food.svg';
```

### Expected behavior

It works in create-create-app

### Actual behavior

```Error in ./src/menu/menu.tsx
(8,18): error TS2307: Cannot find module './food.svg'.
```

### Environment

os: OSX
node: 7.7.1
yarn: 0.21.3
react-scripts-ts: 1.1.8

**Comment by wmonk** [comment]
This is a Typescript this - please see this thread https://github.com/Microsoft/TypeScript/issues/6615. Essentially you need to use `require` as imports something as an `any` and means TS won't try and type it.

**Comment by JamesJefferyUK** [comment]
Exactly the same issue. `require` works but remember to install the types:

`yarn add @types/node --save-dev`
