### ISSUE TITLE
2.16.0 requires tsconfig.prod.json

### ISSUE THREAD

**Issue by lookfirst** [wmonk/create-react-app-typescript#322]
Nothing mentioned in the [migration](https://github.com/wmonk/create-react-app-typescript#migration) document.

```
react-scripts-ts build
(node:94) ExperimentalWarning: The fs.promises API is experimental
Creating an optimized production build...
Failed to compile.

Cannot find "/tsconfig.prod.json" file. Please check webpack and ForkTsCheckerWebpackPlugin configuration. 
Possible errors: 
  - wrong `context` directory in webpack configuration (if `tsconfig` is not set or is a relative path in fork plugin configuration)
  - wrong `tsconfig` path in fork plugin configuration (should be a relative or absolute path)
```

**Comment by DorianGrey** [comment]
Sorry for that - I've updated the docs accordingly.

**Comment by lookfirst** [comment]
@DorianGrey Thanks for the fast resolution. Why not just modify `react-scripts-ts build` to generate the file if it doesn't exist?

**Comment by DorianGrey** [comment]
It'd be dead code later on. I've considered this, but then thought it would not be that overwhelming complex  to create a new file - at least in case it is documented which and how (which I simply forgot, unluckily).

**Comment by BrettKoenig** [comment]
Why is this file needed? Is this a dependency of an npm package the project is using or this project specifically?

**Comment by DorianGrey** [comment]
We received some requests to add the ability to use different `typescript` configurations for development and production mode. This requires different `tsconfig` files, even though one might extend the other. In the default version provided by the template, the `tsconfig.prod.json` simply extends `tsconfig.json` without further changes. However, both might be adopted to more specific use cases if required.

The functionality was added in this PR: https://github.com/wmonk/create-react-app-typescript/pull/299
