### ISSUE TITLE
Support for compilerOptions from tsconfig.json in Jest-Tests?

### ISSUE THREAD

**Issue by luhmann** [wmonk/create-react-app-typescript#33]
I am using Decorators in my app and would like to unit-test the functions that use them. You currently pass a fixed config-object into the ts-compiler that transforms the files before running them trough jest here: https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/config/jest/typescriptTransform.js#L10

```js
// Copyright 2004-present Facebook. All Rights Reserved.

const tsc = require('typescript');

module.exports = {
  process(src, path) {
    if (path.endsWith('.ts') || path.endsWith('.tsx')) {
      return tsc.transpile(
        src,
        {
          module: tsc.ModuleKind.CommonJS,
          jsx: tsc.JsxEmit.React,
        },
        path,
        []
      );
    }
    return src;
  },
};
```

This breaks my tests, because I need to have `experimentalDecorators: true` in there. I ejected the app and verified that this would indeed work.

Is there an easy way to use the `compilerOptions`-settings from the `tsconfig.json` in the project-root or overwrite the settings somehow?

**Comment by wmonk** [comment]
I'm not sure off the top of my head, but would gladly accept a PR for this!
