### ISSUE TITLE
Adding custom config for babel

### ISSUE THREAD

**Issue by seleckis** [wmonk/create-react-app-typescript#345]
I want to use `babel-plugin-styled-components`. To enable this I need to add configuration like this:
```
{
  "plugins": [
    ["babel-plugin-styled-components", {
      "displayName": false
    }]
  ]
}
```
in .babelrc. But there is no .babelrc in this project.

Is it possible to add babel config params without ejecting react scripts?

**Comment by davidbaiguini** [comment]
Have a look here: https://github.com/timarney/react-app-rewired

You can as create your own version of react-scripts as well as per the documentation here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#alternatives-to-ejecting

**Comment by seleckis** [comment]
Oh, rewired, right. I have used it before but forgot about it. Thank you.
