### ISSUE TITLE
New project: Compilation failure 

### ISSUE THREAD

**Issue by rapilabs** [wmonk/create-react-app-typescript#35]
### Can you reproduce the problem with latest npm?

Used yarn 0.21.3

### Description

Created a new project, ran yarn start and get the following:

```
Failed to compile.

Error in Invalid or unexpected token
 @ multi main
```

### Expected behavior

Hello world to show

### Actual behavior

Above error

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts` (if you haven’t ejected):
``` 
my-app@0.1.0 /path/to/my-app
└── (empty)
```

2. `node -v`: v7.7.3
3. `npm -v`: (yarn) 0.21.3

Then, specify:

1. Operating system: mac
2. Browser and version: irrelevant

**Comment by wmonk** [comment]
Hey, did you get this fixed? Do you have a repo I can try this out on?
