### ISSUE TITLE
Upgrading typescript version (question)

### ISSUE THREAD

**Issue by lidermanrony** [wmonk/create-react-app-typescript#361]
How can i update the typescript version?
I have a dependency library (mobx) whose d.ts file uses a 2.7-only feature (unique symbol).
This causes my project to not compile.

**Comment by elektronik2k5** [comment]
You should have no trouble doing that. Personally I'm on an old version of `react-scripts-ts@2.8`, but with the latest `typescript@2.9.2`.
Furthermore, the latest `react-scripts-ts` actually declares `typescript@2.7.1` as devDependency and `typescript@2` as peerDependency.
https://github.com/wmonk/create-react-app-typescript/blob/e4b1f9424fa14f7aae7f0cbf5fd64e18dd273527/packages/react-scripts/package.json#L65-L68

**Comment by ndglover** [comment]
Do I need to eject to do this upgrade? I don't see any reference to typescript version in my app.
