### ISSUE TITLE
SVG as an svg and not as an image

### ISSUE THREAD

**Issue by CraigglesO** [wmonk/create-react-app-typescript#37]
Have you worked with any webpack loaders that I can import svg without them having to be an image? I am having trouble myself.

**Comment by wmonk** [comment]
Not sure what you mean? Maybe raw-loader is what you want?

**Comment by yoiang** [comment]
This was accomplished here in `create-react-app` and would be a gem to have brought over:
https://github.com/facebook/create-react-app/commit/82907fd23cd2a521c3b6c14316ea4177841ede3d

The discussion: https://github.com/facebook/create-react-app/issues/1388

**Comment by maracuja-juice** [comment]
Related to # 1388: https://github.com/facebook/create-react-app/issues/3856

**Comment by wmonk** [comment]
Those look to be coming in the next major version of react-scripts, so we will see then.
