### ISSUE TITLE
Ejecting hardcodes your absolute project path in `package.json`.

### ISSUE THREAD

**Issue by macbem** [wmonk/create-react-app-typescript#379]
In order to reproduce, eject and open `package.json` :) 

Look for the `jest.globals['ts-jest'].tsConfigFile` key - it should be a relative path, like `./tsconfig.test.json`. Instead, it puts an absolute path there, like `/Users/user/coding/test-proj/tsconfig.test.json`. 

This is fine for small projects that you won't share with anyone, but as soon as other people have to work on that project or you want to set up a CI/CD process that runs your tests, you'll get errors related to that path not existing on other people's machines.

So, IMO this is pretty short-sighted. What do you think about it?

**Comment by r3nya** [comment]
Hey @macbem!

Faced with this issue as well.
Will be fix in https://github.com/wmonk/create-react-app-typescript/pull/409 (I hope). :)

Thanks!
