### ISSUE TITLE
Jest test fail: Claims there aren't any tests when there are

### ISSUE THREAD

**Issue by FredrikNoren** [wmonk/create-react-app-typescript#38]
If you are reporting a bug, please fill in below. Otherwise feel free to remove this template entirely.

### Can you reproduce the problem with latest npm?
Yes, I'm on yarn 0.21.3

### Description
`yarn test` gives me "Your test suite must contain at least one test." even though I have a test.

### Expected behavior
`yarn test` should show me 1 test succeeded. 

### Actual behavior
```sh
 FAIL  tests/all.test.js
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at onResult (node_modules/jest-cli/build/TestRunner.js:189:18)
      at process._tickCallback (internal/process/next_tick.js:109:7)

Test Suites: 1 failed, 1 total
```

### Environment

```sh
~/GitHub/nnbuilder/bug-app$ npm ls react-scripts
bug-app@0.1.0 /Users/noren/GitHub/nnbuilder/bug-app
└── (empty)
~/GitHub/nnbuilder/bug-app$ node -v
v7.7.2
~/GitHub/nnbuilder/bug-app$ npm -v
4.1.2
~/GitHub/nnbuilder/bug-app$ yarn --version
0.21.3
```

1. Operating system: OSX
2. Browser and version: Chrome

### Reproducible Demo

See this: https://github.com/FredrikNoren/bug-ts-jest

It's just vanilla `create-react-app-ts` and then that single test added. Run `yarn test` in that app to repro.

**Comment by wmonk** [comment]
hey, have you got any updates on this issue?

**Comment by FredrikNoren** [comment]
Hm sorry missed this. It seems to work now for my. I suspect maybe a different global typescript version or something like that. I'll close for now
