### ISSUE TITLE
Adding typesyle for styling components

### ISSUE THREAD

**Issue by aa6864** [wmonk/create-react-app-typescript#398]
I installed typestyle with `npm install --save-dev typestyle` to add styles in the the Typescript files and the web app in the dev environment is working as expected. However when I run `npm run build` to generate the minified css file I don't see the style in the file. I'm just wondering if I anyone had a similar experience! Do I need to install a loader for the typestyle as well?

**Comment by xaviergonz** [comment]
typestyle is css inside js, it won't generate a css file, it will just generate a class name in runtime and append that css code to a <style> tag in the head (again at runtime)

**Comment by aa6864** [comment]
Thank you @xaviergonz. That makes sense now.
