### ISSUE TITLE
How to import a JSON file

### ISSUE THREAD

**Issue by nareshbhatia** [wmonk/create-react-app-typescript#404]
I am trying to import a JSON file as follows:

    import taskData from './task-data.json';

However I am getting the following error:

> Cannot find module './task-data.json'

I know that the file is there. What am I doing wrong?

P.S. I know that this is possible in create-react-app

**Comment by r3nya** [comment]
Hey @nareshbhatia!

You need to create TS definition file for it, e.g. `typings.d.ts` and add this line:
```js
declare module "*.json" {
    const value: any;
    export default value;
}
```
And after it:
```js
import * as data from './example.json';
```

Please let me know if you will have any problems.

**Comment by r3nya** [comment]
Hey @nareshbhatia! Any news?

**Comment by nareshbhatia** [comment]
I will check it out today. Sorry, was distracted by other priorities.

**Comment by nareshbhatia** [comment]
@r3nya, yes it works! The only tricky bit was that I had to assert the type of `data` to `any`:

    const person = data as any;

Now I could code like this:

    Hello {person.name}! How's the weather in {person.city}?

Without the type assertion I was getting compilation errors.

Thanks again for your help.

**Comment by r3nya** [comment]
🤗

**Comment by shinde-prasad** [comment]
@r3nya is it possible for you to demo with any framework lets say angular5 on plunkr or something on github repo?

**Comment by r3nya** [comment]
Hey @shinde-prasad !
Yeah, I can do it. :)

**Comment by shinde-prasad** [comment]
@r3nya can you please show me a demo? I have tried its giving error module not found for file './data.json'

**Comment by r3nya** [comment]
@shinde-prasad can you share your `tsconfig` for me?
