### ISSUE TITLE
Downgrade packages 

### ISSUE THREAD

**Issue by msirocki** [wmonk/create-react-app-typescript#418]
Why? 

https://github.com/wmonk/create-react-app-typescript/commit/92b112a35e319cd3c7ed3960ee90b4f158a32d82#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by VasilyShelkov** [comment]
This has caused an issue in particular with `Jest` going from `22.3.4` => `20.0.4` where https://jestjs.io/docs/en/jest-object#jestrestoreallmocks is not available in `20.0.4`

**Comment by msirocki** [comment]
Yes, I have same issue.
My tests are broken because jest.fn().mockName() is undefined.

Is the only solution is fix broken tests?

**Comment by VasilyShelkov** [comment]
I've just reverted until this gets sorted out or the major upgrade gets properly documented... I'm also expecting CRA 2.0 to get merged in somehow too so probably will wait until that to upgrade

**Comment by msirocki** [comment]
So I'll wait for upgrade to CRA 2.0

@VasilyShelkov Thanks for the advice!
