### ISSUE TITLE
How to deal with tslint "requires type checking" warnings

### ISSUE THREAD

**Issue by johannespetzold** [wmonk/create-react-app-typescript#42]
Thanks for creating and maintaining the typescript version of create-react-app! I'm new to all of this and it's been a great help.

My question - during build, I get warnings like the following:
```
Warning: The 'await-promise' rule requires type checking
Warning: The 'no-use-before-declare' rule requires type checking
Warning: The 'return-undefined' rule requires type checking
Warning: The 'no-floating-promises' rule requires type checking
Warning: The 'no-unnecessary-qualifier' rule requires type checking
Warning: The 'strict-type-predicates' rule requires type checking
```

(I'm using the [tslint "standard"](https://github.com/blakeembrey/tslint-config-standard) configuration.)

Is there any way to get rid of these warnings (without ejecting)? My understanding is that one has to run `tslint` with the `--type-check` option, but I'm not sure if create-react-app(-typescript) provides any hooks for that.

Thanks for any help!

**Comment by johannespetzold** [comment]
Thanks @jquintozamora. This will work but I was hoping to get the checks to actually run rather than disabling them. But I understand that one gives up configurability by using create-react-app, so if that's not possible so be it. Just wanted to see if that's indeed the case.

**Comment by miracle2k** [comment]
I think for this we'd need to enable the typeCheck option in https://github.com/wbuchwalter/tslint-loader
