### ISSUE TITLE
Update to typescript 2.2?

### ISSUE THREAD

**Issue by TobiasBales** [wmonk/create-react-app-typescript#43]
Is there anything from stopping this happening/getting it merged?

Otherwise I'd take a look in the coming days

**Comment by wmonk** [comment]
On my side, just time! Id happily accept a PR for this. 👍

**Comment by KatSick** [comment]
I think we should upgrade TS to 2.3 ;)

**Comment by wmonk** [comment]
This is done now, probably needs an update to 2.2.3!
