### ISSUE TITLE
Non-text characters in tsconfig.json?

### ISSUE THREAD

**Issue by rolodato** [wmonk/create-react-app-typescript#5]
I'm on:

* macOS 10.12.2
* npm 3.10.8
* Node 6.9.1

Running `create-react-app --scripts-version=react-scripts-ts` works just fine, but I noticed a strange character added to the generated tsconfig.json:

![image](https://cloud.githubusercontent.com/assets/829698/21535815/6b889ada-cd59-11e6-88b2-b096b1a01cb1.png)

Apparently it's the bytes `e2 80 a8` as shown in hexdump:

```
$ hexdump -C tsconfig.json

[...]
00000270  61 74 63 68 65 73 22 0a  20 20 5d 0a 7d e2 80 a8  |atches".  ].}...|
00000280  0a 0a                                             |..|
```

This is not causing any issues that I can tell, but it's definitely odd. Thanks!

**Comment by wmonk** [comment]
Interesting! [This is the file in question](https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/tsconfig.json), it's not generated, just copied over. Looks like there is certainly a newline at the end, which I guess is the character you've found above. Would accept a PR to remove this 😄
