### ISSUE TITLE
Webpack 2 support

### ISSUE THREAD

**Issue by jquintozamora** [wmonk/create-react-app-typescript#51]
Hi @wmonk , Good job!
Do you have plans for supporting webpack 2 your dev workflow ?

Thanks!

**Comment by wmonk** [comment]
Hey @jquintozamora, this is tracking the original `react-scripts`, so when they update in `0.10`(i think), then we will too!

**Comment by wmonk** [comment]
merged in #65, and released in v2.0.0. Please file issues for any bugs you might find! :tada:
