### ISSUE TITLE
vscode debugging not working

### ISSUE THREAD

**Issue by cesarvarela** [wmonk/create-react-app-typescript#52]
If I follow the instructions here: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#debugging-in-the-editor
 I can't get breakpoints to work.

 I get the infamous `Breakpoint ignored because generated code not found (source map problem?).` so I think this has to do with sourcemaps not being generated where they should be or something like that.

(Verified that it works with the default `create-react-app`)

**Comment by KyleGobel** [comment]
Typescript is trickier to get to work in the debugger.  I think it has something to do with with the launch.json paths we're using (I don't think they're the ones the default readme shows)  I haven't spent a bunch of time trying to get it to work (yet), but if/when someone does I feel like we should document that somewhere around here :).  

Would love to have this work.

**Comment by eyelidlessness** [comment]
I just figured this out. In your launch.json, change `"webpack:///src/*"` to `"webpack:///./src/*"`.

**Comment by wiredprairie** [comment]
I used this and breakpoints are now working when launching Chrome via VS Code:

    {
        "type": "chrome",
        "request": "launch",
        "name": "Launch Chrome",
        "url": "http://localhost:3000",
        "webRoot": "${workspaceRoot}/src",
        "userDataDir": "${workspaceRoot}/.vscode/chrome",
        "sourceMaps": true,            
        "sourceMapPathOverrides": {
            "webpack:///./src/*": "${webRoot}/*"
        } ,            
        "runtimeArgs": [
            "--disable-session-crashed-bubble",
            "--disable-infobars"
        ]
    }

I also added to `.gitignore`:

```/.vscode/chrome```

**Comment by mindjuice** [comment]
Has anyone manages to get debugging of Jest unit tests working in vscode?

**Comment by wmonk** [comment]
Closing as this hasn't been updated in a while.

**Comment by mlesk** [comment]
Sorry to hit the closed issue, but looks like some progress has been made in this area, see this [CRA issue](https://github.com/facebookincubator/create-react-app/issues/594#issuecomment-323751116). 

Matt Morgis came up with this configuration that is working for me nicely within VS Code 1.17.0 with Node v8.4.0 and react-scripts-ts 2.7.0 I am finally able to run and debug tests directly in vscode.

Here is the vscode launch command that is working, the only change from original posted is changing reference from react-scripts to react-scripts-ts:

```json
{
    "version": "0.2.0",
    "configurations": [
      {
        "name": "Debug CRA Tests",
        "type": "node",
        "request": "launch",
        "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/react-scripts-ts",
        "runtimeArgs": [
          "--inspect-brk",
          "test"
        ],
        "args": [
          "--runInBand",
          "--no-cache",
          "--env=jsdom"
        ],
        "cwd": "${workspaceRoot}",
        "protocol": "inspector",
        "console": "integratedTerminal",
        "internalConsoleOptions": "neverOpen"
      }
    ]
}

**Comment by QuantumInformation** [comment]
@mindjuice did you have any luck debugging Jest unit tests?

I'm not having any luck with Webstorm:

There is not option to point to a Jest file

![image](https://user-images.githubusercontent.com/216566/32785614-df2b5abc-c949-11e7-9fa6-269958044cda.png)

Like you do in CRA-js
![image](https://user-images.githubusercontent.com/216566/32785667-fc51c3ce-c949-11e7-80e2-4eb48ef1959d.png)

**Comment by steranka** [comment]
I tried doing this on CentOS 7 with vscode and chromium-browser but got the error that type="chrome" was not supported

**Comment by Jonatthu** [comment]
This is still happening to me :/

**Comment by darbio** [comment]
I still am not able to hit breakpoints in vs code using the suggested `launch.json`:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceRoot}/src",
      "userDataDir": "${workspaceRoot}/.vscode/chrome",
      "sourceMaps": true,
      "sourceMapPathOverrides": {
        "webpack:///./src/*": "${webRoot}/*"
      },
      "runtimeArgs": ["--disable-session-crashed-bubble", "--disable-infobars"]
    }
  ]
}

```
