### ISSUE TITLE
Update webpack v2

### ISSUE THREAD

**Issue by rohmanhm** [wmonk/create-react-app-typescript#57]
Please to update webpack version

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

**Comment by wmonk** [comment]
Please look for other webpack 2 issues. This will happen once create-react-app changes to webpack 2.

**Comment by wmonk** [comment]
merged in #65, and released in v2.0.0. Please file issues for any bugs you might find! :tada:
