### ISSUE TITLE
Upgrade to 1.0.0 create-react-app

### ISSUE THREAD

**Issue by KatSick** [wmonk/create-react-app-typescript#58]
I create issue to monitor status of upgrading to new CRA.

**Comment by KatSick** [comment]
Also, i will try to create PR. If someone also interested in this, please, contact me here.

**Comment by Havret** [comment]
+1

**Comment by wmonk** [comment]
Working on it

**Comment by rohmanhm** [comment]
Why this issue has been closed?

**Comment by MaxOrelus** [comment]
+1

**Comment by TobiasBales** [comment]
I think because it is being worked on in pr #59

**Comment by wmonk** [comment]
merged in #65, and released in v2.0.0. Please file issues for any bugs you might find! :tada:
