### ISSUE TITLE
Remove mentions of Eslint

### ISSUE THREAD

**Issue by wmonk** [wmonk/create-react-app-typescript#6]
There are various mentions of `eslint`: 

```
package.json
10-  "bugs": {
11-    "url": "https://github.com/wmonk/create-react-app/issues"
12-  },
13-  "files": [
14-    ".babelrc",
15:    ".eslintrc",
16-    "config",
17-    "bin",
18-    "scripts",
19-    "template",
20-    "utils"

scripts/start.js
125-      console.log();
126-      messages.warnings.forEach(message => {
127-        console.log(message);
128-        console.log();
129-      });
130:      // Teach some ESLint tricks.
131-      console.log('You may use special comments to disable some warnings.');
132:      console.log('Use ' + chalk.yellow('// eslint-disable-next-line') + ' to ignore the next line.');
133:      console.log('Use ' + chalk.yellow('/* eslint-disable */') + ' to ignore all warnings in a file.');
134-    }
135-  });
136-}
137-
```

These should be removed/replaced with `tslint`, and it's corresponding config.

**Comment by chasecaleb** [comment]
Looks like this snuck back in. I'm seeing this in the current version of react-scripts-ts (2.14.0). I'm assuming it's coming from one of these two places in master:
- https://github.com/wmonk/create-react-app-typescript/blob/021b42ad90529d4fee3ca1c19b765487e2a6e994/packages/react-dev-utils/WebpackDevServerUtils.js#L186
- https://github.com/wmonk/create-react-app-typescript/blob/021b42ad90529d4fee3ca1c19b765487e2a6e994/packages/react-scripts/scripts/build.js#L74
