### ISSUE TITLE
Migrate ts-loader to awesome-typescript-loader

### ISSUE THREAD

**Issue by Havret** [wmonk/create-react-app-typescript#60]
Would you consider switching ts-loader to [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader)?

**Comment by wmonk** [comment]
I'm open to it for sure. What benefits would we get from switching?

**Comment by wmonk** [comment]
Read their readme, seems reasonable. Once we merge cra@1 then let's do it.

**Comment by Havret** [comment]
Looking forward for it! :)

**Comment by wmonk** [comment]
@Havret, we are all updated, so if you want to open a PR, now would be a good time!

**Comment by wmonk** [comment]
We are tracking this in #74
