### ISSUE TITLE
Upgrade to create-react-app@1.0.0

### ISSUE THREAD

**Issue by AJamesPhillips** [wmonk/create-react-app-typescript#61]
The [1.0.0 canary build](https://github.com/facebookincubator/create-react-app/issues/2172) is out.  I was wondering if you were happy tackling upgrading to this when it's ready or if you wanted some to take the lead @wmonk ?  Thanks for the great work.  Really helpful.

**Comment by Havret** [comment]
@wmonk is working on it https://github.com/wmonk/create-react-app-typescript/issues/58

**Comment by wmonk** [comment]
merged in #65, and released in v2.0.0. Please file issues for any bugs you might find! :tada:
