### ISSUE TITLE
Works with the new updated create-react-app ?

### ISSUE THREAD

**Issue by appsolutegeek** [wmonk/create-react-app-typescript#63]
Hi,

Recently the create react app was updated to use webpack 2 etc.

Does this script play nice with it or do we need to wait for an update ?

Thanks in advance

**Comment by Havret** [comment]
We need to wait for an update, and @wmonk is working on it https://github.com/wmonk/create-react-app-typescript/issues/58.

**Comment by appsolutegeek** [comment]
Great - thanks!

**Comment by wmonk** [comment]
Merged in #65, and released in 2.0.0. Please update with any bugs you find! 🎉
