### ISSUE TITLE
Jest can't run all tests after updatein to cra-ts 2.0

### ISSUE THREAD

**Issue by TobiasBales** [wmonk/create-react-app-typescript#66]
When starting the jest test running and hitting `a` to run all test for me (after an upgrade, without changing anything) checks for tests in `<project>/src/**/__tests__/**/*.js?(x),<project>/src/**/?(*.)(spec|test).js?(x)` which obviously does not match `.ts/.tsx` files

I would guess that the config option should be overridden by cra-ts

**Comment by wmonk** [comment]
Thanks, will fix now!

**Comment by TobiasBales** [comment]
For all the people having an issue, you can temporarily call jest with `--testMatch='**/__tests__/**/*.ts?(x)'` (e.g. in your package.json) to work around it for now

**Comment by wmonk** [comment]
Should be fixed now in 2.0.1!
