### ISSUE TITLE
Loading image from public folder seems to cause error

### ISSUE THREAD

**Issue by MaxOrelus** [wmonk/create-react-app-typescript#69]
Module not found: You attempted to import `../../../public/assets/logo.png` which falls outside of the project `src/` directory. Relative imports outside of `src/` are not supported. You can either move it inside `src/`, or add a symlink to it from project's `node_modules/`.

This use to work before the latest commit. I have images that get referenced in my scss files. Since this doesn't work now, is there an alternative to how to reach image in public folder?

**Comment by Havret** [comment]
It comes with the recent update. For faster rebuilds, only files inside src are processed by Webpack. You need to put any JS and CSS files inside src, or Webpack won’t see them.

**Comment by wmonk** [comment]
Yes as @Havret says, this is a new decision by `create-react-app`. You will have to move anything that you want to compile into the `src` directory.

**Comment by ayepRahman** [comment]
guys even i place a img folder in the /src iam still haaving the same issues

/src/img/img-examples.jpg

and i tried importing the imgae using sass

**Comment by corke** [comment]
Same as @ayepRahman, you find a way ?

**Comment by Ankit09osr** [comment]
guys you have to give a path relative to where your style.css and not relative to sass file. Because .css file is the one that is being used by index.html when loading the application.

**Comment by mdmasumbillah** [comment]
@ayepRahman I'm same issue.

**Comment by M-Ghaith** [comment]
Is this issue been solved??
