### ISSUE TITLE
Go Ahead

### ISSUE THREAD

**Issue by rohmanhm** [wmonk/create-react-app-typescript#70]
> This branch is 205 commits ahead, 9 commits behind facebookincubator:master.

You know what I mean 😄. We still behind

**Comment by Havret** [comment]
Were there any reasons why we didn't catch up the master branch with recent upgrade?

**Comment by wmonk** [comment]
Just timings, cra released a bunch of fixes as I was doing the massive merge, so didn't catch everything. Just working to merge in `1.6.0` from cra.
