### ISSUE TITLE
Typescript 2.3.3

### ISSUE THREAD

**Issue by sjdweb** [wmonk/create-react-app-typescript#71]
Is it possible to upgrade? This issue is affecting my new project: https://github.com/Microsoft/TypeScript/issues/15463.

Only seems to happen when trying to use redux `connect()`

**Comment by wmonk** [comment]
Will accept a pr for this

**Comment by wmonk** [comment]
Assuming you're asking for an upgrade to typescript??

**Comment by sjdweb** [comment]
Yes - I will submit a PR shortly! Thanks for the speedy reply.

**Comment by sjdweb** [comment]
PR submitted.
