### ISSUE TITLE
Replace style-rules in tslint with prettier

### ISSUE THREAD

**Issue by jacobrask** [wmonk/create-react-app-typescript#77]
[The reasons](https://github.com/facebookincubator/create-react-app/issues/2157#issuecomment-301452953) for not including style only eslint rules in create-react-app are also valid for this project. 

As of 1.4 prettier supports TypeScript so that should be used for code style instead of tslint. The current tslint settings are incompatible with default prettier settings, which is the main reason I noticed this.

**Comment by wmonk** [comment]
I will accept a PR to implement this 👍

**Comment by corydeppen** [comment]
Would you consider using [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier)? I'd be willing to submit the PR if no one else is already working on it.

**Comment by wmonk** [comment]
@corydeppen I don't believe anyone is working on this. Very happy to accept a PR 😄

**Comment by corydeppen** [comment]
It might be good to include this in the work @timjacobi is doing related to #109. Thoughts?

**Comment by wmonk** [comment]
Sounds good, check #112

**Comment by nielsdB97** [comment]
@wmonk I think this can be closed now :)

**Comment by wmonk** [comment]
Thanks!

**Comment by LucienLee** [comment]
Hi, #281 included [tslint-config-prettier](https://github.com/alexjoverm/tslint-config-prettier), which turns off conflict tslint rule with prettier. However, that doesn't enable prettier code style. If we want to use prettier code style, we have to include [tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier). 

@wmonk how do you think? I can make PR for this.

**Comment by DorianGrey** [comment]
@LucienLee: Enforcing this was not the intention of this change. Before it, the TSLint config contained a lot of rules related to opinionated code style, like ' vs ", of stuff about whitespacing. Some of these rules are also enabled by default when using one of the TSLint standard configurations.
The intention was to kick style related rules from the config, e.g. for using tools like `prettier` to format the code automatically. And that config package does a good job for achieving this.
