### ISSUE TITLE
TS cannot find module

### ISSUE THREAD

**Issue by pierre-H** [wmonk/create-react-app-typescript#8]
### Can you reproduce the problem with latest npm?
Yes

### Description
When I try to import another library, I've got the error "TS : cannot find module _libraryName_

### Environment

Run these commands in the project folder and fill in their results:

1. `npm ls react-scripts` (if you haven’t ejected): 
```
C:\Users\Eytan\Documents\tickets>npm ls react-scripts
tickets@0.1.0 C:\Users\Eytan\Documents\tickets
`-- (empty)

npm ERR! code 1
```

2. `node -v`:  v7.3.0
3. `npm -v`: 3.10.10

Then, specify:

1. Operating system: Windows
2. Browser and version: Vivaldi 1.6.689.40 32bits

### Reproducible Demo

```
yarn global add create-react-app
create-react-app my-app --scripts-version=react-scripts-ts
yarn add admin-on-rest
```

Then if I add this line on my code : 
`import { simpleRestClient, Admin, Resource } from 'admin-on-rest';`

I've got the error

**Comment by pierre-H** [comment]
Sorry, this issue is about TS not react-scripts-ts.

**Comment by wmonk** [comment]
Hi Pierre, no problem! Did you manage to sort it yourself by adding typings?

This might raise an interesting addition we could make like the eslint/taking warnings that suggests adding the typings for new packages. Could be useful if there are TS beginners using this.

**Comment by CraigglesO** [comment]
I am using Yarn:

I had an error that said
`cannot find name ' require'`

But it still ran great (to be clear, this error ran inside atom with the atom-typescript plugin)


But this fixed it:
`
  "compilerOptions": {
      ...
      "types": [
        "node"
      ],
      "typeRoots": [
        "node_modules/@types"
      ]
  }
`

I am also having an issue with "cannot find name "it", (app.test.tsx) But I am sure I will find eventually and get back with you.

**Comment by HawiCaesar** [comment]
I had the same problem as @CraigglesO but I managed to get around it. The only issue have is my IDE keeps telling me that `cannot find name "it"` even though the setup and code runs on the browser.
