### ISSUE TITLE
TypeError: Cannot read property '0' of undefined error when used in conjunction with html-webpack-plugin

### ISSUE THREAD

**Issue by seanchen1991** [wmonk/create-react-app-typescript#84]
`react-scripts-ts` doesn't seem to be playing well with `html-webpack-plugin`. [This](https://github.com/facebookincubator/create-react-app/issues/2069) issue seems to have been fixed over in `react-scripts`. Can the fix be propagated over to `react-scripts-ts`?

**Comment by wmonk** [comment]
I can't work out from the issue you linked whether this has been fixed in CRA? 

Which version of `react-scripts-ts` are you using?
