### ISSUE TITLE
Is possible to use these scripts with mocha-chai-enzyme instead of jest?

### ISSUE THREAD

**Issue by CzBuCHi** [wmonk/create-react-app-typescript#86]
Question is in title, here is my reason why:

---
in mocha-chai-enzyme combo i can write test like this:

```js

function TestComponent({ value, doClick }){ // react stateless component
  return (
    <div className="test-component" onClick={ e => doClick(value) }>
      { value && <TestComponent Value={ value - 1 } doClick={ doClick } /> }
    </div>
  );
}

describe('Test', function () {
  it('Success', function () {
    const props = { 
      value: 42, 
      doClick: () => { } // functions are checked only for existence, not content
    };    
    const actual = shallow(<TestComponent {...props} />);    
    const expected = // basically copy-pastle of TestComponent return value...
      <div className="test-component" onClick={ () => { } }>
        <TestComponent Value={ 41 } doClick={ () => { } } />
      </div>;    
    expect(actual).toEqualJSX(expected); // toEqualJSX from './jsxEqual'
  });
});
```

instead of something like:
```js
expect(actual.find('.test-component')).to.have.length(1);
expect(actual.find(TestComponent)).to.have.length(1);
expect(actual.find(TestComponent).props.value).to.be.equal(41);
expect(actual.find(TestComponent).props.doClick).to.be.not.null;
...
```
i dont wanna loose that but also like no-config configuration of cra-ts ....

**Comment by wmonk** [comment]
It isn't possible to use `mocha` but I think it's possible to use `chai-enzyme`. [Airbnb actually released a blog post today](https://medium.com/airbnb-engineering/unlocking-test-performance-migrating-from-mocha-to-jest-2796c508ec50) in which they describe using `chai` with `jest`. So you can just require in `{ expect }` from `chai`.

**Comment by wmonk** [comment]
On a side note, personally I don't think it's valuable to test components in the way you describe above. While I don't use this testing strategy, [Snapshot testing](http://facebook.github.io/jest/docs/en/snapshot-testing.html#snapshot-testing-with-jest) sounds very similar to what you you're doing in your example.

**Comment by CzBuCHi** [comment]
i have zero experience with jest - but snaphots looks really pretty to me :) ... so im guessing i will switch to jest after all :)
