### ISSUE TITLE
[question] Is `regeneratorRuntime` for `async`/`await` available?

### ISSUE THREAD

**Issue by jrehwaldt** [wmonk/create-react-app-typescript#88]
I want to include a package compiled with babel, namely [`redux-middleware-fetch`](https://github.com/fantasywind/redux-middleware-fetch). Because this package is using `async`/`await` it [depends on `regeneratorRuntime` to be available globally](https://github.com/fantasywind/redux-middleware-fetch/blob/master/lib/middleware.js#L87).

My `create-react-app-typescript` project compiles and bundles successfully, but when opened in the browser I get `Uncaught ReferenceError: regeneratorRuntime is not defined`.

Now, I can see that this polyfill is used by `react-error-overlay`:
```
`-- react-scripts-ts@2.2.0
  `-- react-error-overlay@1.0.7
    `-- babel-runtime@6.23.0
      `-- regenerator-runtime@0.10.5
```

Is it possible to include this polyfill globally without ejecting? Alternatively, is it possible to compile the depending package in a away that it does not depend on this polyfill? Any inside? (As I can see from the TypeScript documentation they have support for async/await, which makes me think I could compile the depending package using TypeScript?)

**Comment by wmonk** [comment]
As this issue hasn't been updated for a while, I am going to close it. If there are any updates feel free to re-open and comment. 👍
