### ISSUE TITLE
[Question] What does typesPatches do in tsconfig.json?

### ISSUE THREAD

**Issue by pselden** [wmonk/create-react-app-typescript#89]
https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/tsconfig.json#L30

Just curious what this line does -- I've never seen it before in a project.

**Comment by wmonk** [comment]
This was left over from when I originally created this module. It was a place we stored `.d.ts` files for modules that either didn't have them, were out of data, or were wrong. It should really be removed now. Hope this helps!

**Comment by js-n** [comment]
I'm still seeing it in https://github.com/wmonk/create-react-app-typescript/blob/master/packages/react-scripts/template/tsconfig.json and in new projects generated when I run `create-react-app my-app --scripts-version=react-scripts-ts`.

When you say "it should really be removed now," is that describing current state, or something to do in the future?

Would you accept a PR removing this line?

Thanks!

**Comment by wmonk** [comment]
@js-n I would happily accept a PR for it! 👍
