### ISSUE TITLE
SASS Support

### ISSUE THREAD

**Issue by Oceanswave** [wmonk/create-react-app-typescript#92]
Question about SASS support.

If I follow the official SASS directions at
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc

It seems as though scss files are still not able to be imported.

Is this some thing that should just work, or is ejecting still required if I want to use create-react-app-ts.

Thanks,

**Comment by mikebridge** [comment]
Would it work to import the resulting .css files via an import, e.g. `import "./index.css"`?

**Comment by Oceanswave** [comment]
That does work -  however, it would be nice to reference scss files from /node_modules in order to override scss variables

**Comment by Oceanswave** [comment]
Disregard - didn't have my head on straight. Referencing the .css files that then import the scss files works great.
