### ISSUE TITLE
Use 'typescript-babel-jest' for jest tsx transform

### ISSUE THREAD

**Issue by JiLiZART** [wmonk/create-react-app-typescript#97]
Hi, I have ejected version of cra and had some issues with configuration for jest.

After about 3 hours trying to chain compilation of `babel` and `typescript` I just found `typescript-babel-jest`. Zero configuration drop-in replacement. 

I just changed `"^.+\\.tsx?$": "<rootDir>/config/jest/typescriptTransform.js",` with `"^.+\\.tsx?$": "typescript-babel-jest",` in my `package.json` and it simply works, reads tsconfig.json and .babelrc and other settings!

So I have suggestion for including this package, this guys use it too https://github.com/ant-design/ant-design/blob/master/.jest.js#L33

**Comment by wmonk** [comment]
Hi, is this fixed from us moving to `ts-jest`?

**Comment by JiLiZART** [comment]
Its only suggestion of a good package, that can chain `babel` and `ts`. It's on your choice what package to use. Anyway i solved this for myself

**Comment by wmonk** [comment]
Please close this issue if it is solved 👍
